### PR TITLE
DOC - explicitly run the streamline generators before saving the trk

### PR DESCRIPTION
**Pull request by gabknight**
This addresses #1779 and clarifies the examples.

Any idea on the root of the problem in #1779 ?

### CODE REVIEW

**Comment by skoudoro** [comment]
Nice! Thank you @gabknight! 

> Any idea on the root of the problem in #1779 ?

No idea at the moment, I will look deeper into it this week.

**Comment by arokem** [comment]
An idea: how about if `save_trk` always tried to call `Streamlines` on its input? That way, we could pass it a generator and it would do the right thing.

**Comment by gabknight** [comment]
@arokem `save_trk` accept generators, normally without issues (I cannot reproduce the problem in #1779).  It is actually a good idea to provide a generator as the streamlines will be generated as they are saved, limiting memory issue for a high number of seeds. 

There seems the be corner cases where this fails though.

**Comment by skoudoro** [comment]
Agree with @gabknight.  Thank you for this update! merging

**Pull request merged**
