### PR TITLE
Fixes #979 : No figures in DKI example - commented savefig()

### LINKED ISSUE #979: No figures in DKI example
I think that might be because the call to `plt.show` comes before the call to `savefig` (e.g. here: https://github.com/nipy/dipy/blob/master/doc/examples/reconst_dki.py#L209)

### PR DESCRIPTION
**Pull request by sahmed95**
Commenting out savefig() in the example should render the plots in sphinx.

### CODE REVIEW

**Comment by arokem** [comment]
Did you run the makefile to make sure the html renders properly with this fix?

**Comment by sahmed95** [comment]
Hi, I was building the docs using sphinx. But the datasets are taking a long time to download. Maybe someone who's working on the website can take a look and this can be resolved faster. @ghoshbishakh ?

**Comment by Garyfallidis** [comment]
You can comment (using ``#``) the examples that you do not need in dipy/doc/examples/valid_examples.txt and cd doc; make clean;  make html 
In this way it will be much faster to check how the tutorial that you are interested is renderered.

**Comment by sahmed95** [comment]
Thanks. I will run the makefile and see if the plots are rendering fine. :smile:

**Comment by arokem** [comment]
Any update on this?

**Comment by sahmed95** [comment]
Hi, I commented and ran the make file. But I get stuck everytime at  "Downloading "HARDI150.nii.gz" to /home/shahnawaz/.dipy/stanford_hardi"

I am trying to figure out if its an issue with my connection or something to do with the large file size. I tried to separately download the file from the [link](https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L277) but it shows that file doesn't exist. I am also not able to download sherbrooke_3shell. So I went to the site from [fetcher] (https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L263)

Again ran into a 404 in [dropbox](https://dl.dropboxusercontent.com/u/2481924/sherbrooke_data/)

**Comment by arokem** [comment]
Using just the links on these lines shouldn't work. The links should be used like this:

"https://stacks.stanford.edu/file/druid:yx282xq2090/dwi.nii.gz"
"https://stacks.stanford.edu/file/druid:yx282xq2090/dwi.bvals"
"https://stacks.stanford.edu/file/druid:yx282xq2090/dwi.bvecs"
"https://dl.dropboxusercontent.com/u/2481924/sherbrooke_data/3shells-1000-2000-3500-N193.nii.gz"

etc. 

That said, I do think there's a problem with the recent changes to the fetcher. I'm looking into that right now.

**Comment by ghoshbishakh** [comment]
I hope the progressbar change did not break anything here

**Comment by arokem** [comment]
Alas, I think it has. I am getting this: 

```
In [2]: ans = dpd.read_stanford_hardi()
Creating new folder /Users/arokem/.dipy/stanford_hardi
Downloading "HARDI150.bval" to /Users/arokem/.dipy/stanford_hardi
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-bc0742ca9134> in <module>()
----> 1 ans = dpd.read_stanford_hardi()

/Users/arokem/source/dipy/dipy/data/fetcher.py in read_stanford_hardi()
    466         GradientTable
    467     """
--> 468     files, folder = fetch_stanford_hardi()
    469     fraw = pjoin(folder, 'HARDI150.nii.gz')
    470     fbval = pjoin(folder, 'HARDI150.bval')

/Users/arokem/source/dipy/dipy/data/fetcher.py in fetcher()
    207             files[n] = (baseurl + f, md5_list[i] if
    208                         md5_list is not None else None)
--> 209         fetch_data(files, folder)
    210 
    211         if msg is not None:

/Users/arokem/source/dipy/dipy/data/fetcher.py in fetch_data(files, folder)
    159         all_skip = False
    160         _log('Downloading "%s" to %s' % (f, folder))
--> 161         _get_file_data(fullpath, url)
    162         check_md5(fullpath, md5)
    163     if all_skip:

/Users/arokem/source/dipy/dipy/data/fetcher.py in _get_file_data(fname, url)
    118     with contextlib.closing(urlopen(url)) as opener:
    119         if sys.version_info[0] < 3:
--> 120             response_size = opener.headers['content-length']
    121         else:
    122             # python3.x

/Users/arokem/anaconda/envs/py2/lib/python2.7/rfc822.pyc in __getitem__(self, name)
    391     def __getitem__(self, name):
    392         """Get a specific header, as from a dictionary."""
--> 393         return self.dict[name.lower()]
    394 
    395     def __setitem__(self, name, value):

KeyError: 'content-length'
```

**Comment by sahmed95** [comment]
Might just be a connection issue on my side. I will try to manually
download the files and see. The progress bar is a great feature btw... I
have been staring at the blank line on my terminal for the last 30 mins. :-(

**Comment by ghoshbishakh** [comment]
aaah looking into it!!

**Comment by ghoshbishakh** [comment]
steps to regenerate the issue?

**Comment by arokem** [comment]
On *Python2* (might that be the issue?), move the data folder out of the way. Then: 

    import dipy.data as dpd
    ans = dpd.read_stanford_hardi()

**Comment by sahmed95** [comment]
Yeah. I was running it in Python2.7. Another point to be noted is I can
download the bvalue file. So it might be something with the file headers in
the .nii file.

**Comment by ghoshbishakh** [comment]
ok got the problem. trying to fix it asap! seems sometimes http headers dont have the content-length

**Comment by ghoshbishakh** [comment]
so downloading:
https://stacks.stanford.edu/file/druid:yx282xq2090/dwi.nii.gz
from the browser also does not show the size.

@arokem what do you recommend doing here.

**Comment by arokem** [comment]
So this would never work for this data, correct? What data-set does it work well for?

**Comment by ghoshbishakh** [comment]
So it depends on the server from which it is being served. Simply if we try to download the dataset from the browser using the link and the browser cannot predict the size of the download then it will also not work here, i.e the content-length header is missing.

**Comment by sahmed95** [comment]
Should we open a new issue for this ?

**Comment by arokem** [comment]
Yes - let's move this conversation to #1014

**Comment by sahmed95** [comment]
I ran into one more issue in reconst_dti.py. By commenting all the other files as suggested by @Garyfallidis I got this when I run make html for only reconst_dti.py 

```python
Computing anisotropy measures (FA, MD, RGB)
Computing tensor ellipsoids in a part of the splenium of the CC
Traceback (most recent call last):
  File "../tools/make_examples.py", line 123, in <module>
    execfile(script, namespace)
  File "reconst_dti.py", line 219, in <module>
    ren = fvtk.ren()
AttributeError: 'module' object has no attribute 'ren'
make: *** [rstexamples-stamp] Error 1
```

The issues arises from ```python ren = fvtk.ren ``` and the corresponding import is found [here] (https://github.com/nipy/dipy/blob/master/dipy/viz/fvtk.py#L68) 

have_fvtk comes from the [optional package](https://github.com/nipy/dipy/blob/master/dipy/viz/fvtk.py#L33)

**Comment by arokem** [comment]
Do you have VTK installed? That error often get's thrown when you don't
have VTK: https://neurostars.org/p/3724/#3726

**Comment by sahmed95** [comment]
I tried "make html" but the images are not rendering with plt.show() and commenting savefig(). So I went to the other examples [reconst.dti](http://nipy.sourceforge.net/dipy/examples_built/reconst_dti.html#example-reconst-dti) and saw that fvtk is used for rendering plots. Why is the case different here? Is this the reason why we are not getting plots in dki?

P.S. Good thing this happened, there's one more issue I found with VTK not being installed. Please have a look at #1017

**Comment by arokem** [comment]
There are several examples that use matplotlib, without a hitch. For example: http://nipy.org/dipy/examples_built/brain_extraction_dwi.html#example-brain-extraction-dwi

**Comment by arokem** [comment]
So no - I wouldn't change this to use fvtk. We can certainly use matplotlib here as well.

**Comment by sahmed95** [comment]
Ok. Thanks. I will see why it is not rendering here with matplotlib.

**Comment by sahmed95** [comment]
@arokem @Garyfallidis Solved the plotting issue. I didn't have to remove savefig(). It was just a matter of incorrect syntax for rst files. According to the [documentation](http://docutils.sourceforge.net/docs/ref/rst/directives.html#figure), after the figure directive, there should be a new line before image description. I tried make html and got the plots. 

The power of a "\n" !! Got a good nice intro to sphinx :smile:

**Comment by arokem** [comment]
Fantastic! They don't call it "sphinx" for nothing - cryptic, mysterious and powerful! @Garyfallidis : do we have a plan for merging upstream fixes into the current web-page? Do we cherry pick these fixes into maint/0.11.x and build the website from that?

**Comment by manu-tej** [comment]
That was the same problem for #1024

**Comment by arokem** [comment]
Also white-space, but seems to be in a different part of the file...

**Pull request merged**
