### PR TITLE
Update deprecated function.  

### PR DESCRIPTION
**Pull request by skoudoro**
get_header() / get_affine() method is deprecated from nibabel 2.1, we use header / affine property instead

### CODE REVIEW

**Comment by arokem** [comment]
Thanks for doing this! I just noticed this in running tests on my machine as well. Let's see how Travis takes to it.

**Comment by arokem** [comment]
Great! Seems to work fine, even with relatively elderly nibable: https://travis-ci.org/nipy/dipy/jobs/171644798

I am +1 here, but I will let others take a look as well (and merge in a few days if no one has anything to say about it).

**Comment by Garyfallidis** [comment]
:+1:  from me too. Thank you @skoudoro :)

**Comment by skoudoro** [comment]
no problem :)

**Pull request merged**
