### PR TITLE
Robust Brain Extraction

### PR DESCRIPTION
**Pull request by riddhishb**
This PR will mark the start of some work in template based brain extraction as a part google summer of code 2016.
Currently only two changes
1) Added a new function `brain_extraction` in dipy.segment.mask
2) Added a tutorial in doc/examples

All the tests and refinement will be coming along in this month

### CODE REVIEW

**Comment by riddhishb** [comment]
Rebased with the master

**Comment by fmorency** [comment]
Hi,

Thanks for working on this feature. I installed your dipy branch in a fresh virtualenv containing

- Cython (0.24.1)
- dipy (0.12.0.dev0)
- docopt (0.6.2)
- nibabel (2.1.0)
- numpy (1.11.1)
- pip (6.1.1)
- scipy (0.18.0)
- setuptools (15.0)

I wrote a little callable script to be able to extract brains [1] from the command line and tested your feature on some T1/B0 [2] using the OASIS-30 [3] template (with cerebellum [4]). 

The problem is that the brain/mask obtained in **all** my tests are empty. I tried T1 on T1 and B0 on T1. Any idea on what is causing this?

  [1]: https://www.dropbox.com/s/66cb250j4j8cpd4/extract_brain.py?dl=0
  [2]: https://www.dropbox.com/sh/jycy8q8dp54sa9t/AAAy7sTspMXG9nI0SSVPZkQAa?dl=0
  [3]: http://www.mindboggle.info/
  [4]: https://www.dropbox.com/sh/or6cjiglq7gyjji/AADrCbVdrGKBiZeY6HGBlvyIa?dl=0

Thanks,
-F

**Comment by riddhishb** [comment]
@fmorency Let me try with your data and I will get back to you, ideally there shouldn't be any problems.

**Comment by riddhishb** [comment]
@fmorency I dont know what is wrong with it. But I am getting this (correct extraction output)
screen shot 2016-08-26 at 11 59 03 am

And I am using the code and the files as given here
https://www.dropbox.com/sh/wl362aqu03pmhn0/AAA26kfGFmt-nMsXenhVRtN7a?dl=0

**Comment by fmorency** [comment]
Ok, I've been able to get some non-empty results with my script [1]. You should probably check for patch/block radius and threshold minimal value and throw an exception if the value is <= 0.

Some quick questions/comments

  1) Ventricles are always absent from the brain mask when processing most of my T1. Why?
  2) What database did you use to test your algorithm? Most of the data I'm trying to segment (different scanners, different pathologies, etc) always have a little something that is wrong (mask too aggressive, missing brain region, part of the skull still present, etc). I still haven't found a set of parameters that works well on T1, for example. What are your thoughts on this?

  [1]: https://www.dropbox.com/s/tw5oh0pi22gtebh/extract_brain.py?dl=0

**Comment by riddhishb** [comment]
@fmorency I am really sorry for the late reply
I will look into the patch-block exception, thanks a lot for pointing that out.
As for your questions
1) I do not have any idea about this phenomena I think @RafaelNH or @Garyfallidis may be able to help you here.
2) You can have a look at the following posts ( [1](https://riddhishbgsoc2016.wordpress.com/2016/08/08/polishing/) and [2](https://riddhishbgsoc2016.wordpress.com/2016/07/25/brain-extraction-explained/) ) for all the data and params I use for testing. The testing process is still ongoing, we would like to experiment on more datasets and improve the algorithm if possible, hopefully we can finish this off in coming few weeks :)

**Comment by fmorency** [comment]
@riddhishb I performed a test run on ISBR_01 using FSL, AFNI, ANTs and dipy-brain extraction. Results can be found in [1]. A file named "call" can be found in each folder and contains the command-line ran. Template (OASIS-30 with cerebellum) used for ANTs and dipy-brain-extraction can be found in [2]. Binary for dipy-brain-extraction can be found in [3].

As you can see, results from dipy-brain-extraction are often missing regions compared to other methods/ground truth.

[1]: https://www.dropbox.com/sh/5h8uh1vq1n4yl1t/AACpd_V89zSVBNt0XKazLbCWa?dl=0
[2]: https://www.dropbox.com/sh/or6cjiglq7gyjji/AADrCbVdrGKBiZeY6HGBlvyIa?dl=0
[3]: https://www.dropbox.com/s/tw5oh0pi22gtebh/extract_brain.py?dl=0

**Comment by Garyfallidis** [comment]
@riddhishb have you looked into these results reported by @fmorency? Thanks @fmorency for the feedback.

**Comment by Garyfallidis** [comment]
Also just something to make clear here. During GSoC we didn't have the time to compare against other tools. But we did compare against simulated brains (IBSR) with given masks. The main idea was to put some existing tools together so we can do some brain extraction. Actually, it was impressive that we had a working prototype so fast. Now we should try to look into the details. These results that you are providing @fmorency I think they will be useful. @riddhishb what do you think?

**Comment by riddhishb** [comment]
Yeah I think thats the plan! In fact we have to do some nice comparisons, against other methods. Brain extraction functionality in DIPY was just limited to median otsu before this PR, so there is a lot of room for improvement.

**Comment by arokem** [comment]
This work seems to have stalled. Closing

**Pull request closed without merging**
