### PR TITLE
STYLE: PEP8 for workflows folder

### PR DESCRIPTION
**Pull request by hokatvcu**
STYLE: pep8 fixes for workflow folder.

### CODE REVIEW

**Comment by arokem** [comment]
Nice work! Still remaining for these files:

    dipy/workflows/tests/test_iap.py:33:12: E127 continuation line over-indented for visual indent
    dipy/workflows/tests/test_iap.py:34:12: E127 continuation line over-indented for visual indent

You might want to use the pep8 program (https://pypi.python.org/pypi/pep8) or a pep8-enabled editor (https://atom.io/packages/linter-pep8) to check.

**Comment by arokem** [comment]
For #896

**Comment by arokem** [comment]
@hokatvcu - did you mean to close this, or do you want us to merge this?

**Comment by hokatvcu** [comment]
close it please.

**Comment by sahmed95** [comment]
#930 pep8 fix

**Pull request closed without merging**
