### PR TITLE
Upgrade nibabel minimum version

### PR DESCRIPTION
**Pull request by skoudoro**
Due to a memory issue on Streamlines, this is a proposition to upgrade the Nibabel minimal version.

### CODE REVIEW

**Comment by arokem** [comment]
In general +1 from me!

Could you point out relevant issues/PRs on nibabel that clarify what the memory issues are?

**Comment by skoudoro** [comment]
yes, this is PR https://github.com/nipy/nibabel/pull/597

**Comment by skoudoro** [comment]
BTW, `Numpy` released 2 days ago...  and scipy did not release yet the fix #1565 so I think, all our PRs will failed from now until the scipy release. What should we do ?

**Comment by arokem** [comment]
Can we patch in the scipy fix into our source tree for now?

**Comment by skoudoro** [comment]
I do not think so or I do not know how

**Comment by arokem** [comment]
Basically, I think that we need to create our own fftpack file, that
includes these changes:

https://github.com/scipy/scipy/pull/8879/files

Or are you referring to the numpy error (The one resulting in `ValueError:
The truth value of an array with more than one element is ambiguous. Use
a.any() or a.all()`)?

Is there any fix for that one anywhere (e.g., on numpy)?

`

**Comment by skoudoro** [comment]
> Or are you referring to the numpy error (The one resulting in `ValueError:
The truth value of an array with more than one element is ambiguous. Use
a.any() or a.all()`)

that one was a cython error which has been corrected (#1579)

**Comment by arokem** [comment]
OK - so patching in our own version of fftpack (with the fixes from https://github.com/scipy/scipy/pull/8879/files) should do the trick.

**Comment by arokem** [comment]
Does anyone else have any input on this one? 

@matthew-brett : any reason you can think of not to update the dependencies to nibabel 2.3.0?

**Comment by matthew-brett** [comment]
No reason I can think of.

**Comment by arokem** [comment]
Off we go, then!

**Pull request merged**
