### PR TITLE
Automate script installation

### PR DESCRIPTION
**Pull request by skoudoro**
resolving #1253 : find files recursively instead of static files list for automating script installation

### CODE REVIEW

**Comment by arokem** [comment]
Yeah - this looks good to me. It seems to be in conflict with master. Could you please rebase?

**Comment by Garyfallidis** [comment]
We just used the resolve conflict button. Which actually does a merge not a rebase.

**Comment by Garyfallidis** [comment]
That was just a test. We were not sure what the resolve button was doing. Next time we rebase. For this time it will probably be okay as the conflict and commit history was small.

**Comment by Garyfallidis** [comment]
This looks ready to me. Any objections?

**Pull request merged**
