### PR TITLE
Added File Menu element to viz.ui

### PR DESCRIPTION
**Pull request by karandeepSJ**
Added a `FileMenu2D` that uses a `ListBox2D` to display all files and directories in the file system. Files are shown with Blue color and directories with Green. Clicking on a directory will take the user inside it.

filemenu

### CODE REVIEW

**Comment by MarcCote** [comment]
I think this code could be more concise if it was not reimplementing scrolling and selection logic as it is already managed by the ListBox component.

Here my version (still WIP) that could use as a start point: https://github.com/nipy/dipy/compare/master...MarcCote:enh_ui_filedialog3

**Comment by karandeepSJ** [comment]
It's not reimplementing them. There are additional tasks that need to be done on scrolling and clicks, so I added more callbacks. For scrolling, we need to update the colors of the text in the slots, so the `scroll_callback` is handling that.

**Comment by MarcCote** [comment]
I see. Maybe it would be better (more modular) to have that logic in ListBox no? 

We could have a list of "representation" along the values for all items in the list. Then, whenever an item needs to be displayed, we update its slots according to its values (already doing this) and representation (need to be implemented). That way would offer a modular approach to use special representation for files/folders in the FileMenu.

**Comment by karandeepSJ** [comment]
What could be the possible uses for a ListBox that require different representations?

**Comment by MarcCote** [comment]
It could allow a user to define which colors should be used to highlight the different items in the listbox (like you are doing for FileMenu).

**Comment by karandeepSJ** [comment]
Should I keep representation as a list of colors?

**Comment by arokem** [comment]
Indeed, this fixes the error that was on master. The remaining error is due to #1565, so I will go ahead and merge this.

**Comment by karandeepSJ** [comment]
Wrong PR :P. The one you want is #1574

**Comment by arokem** [comment]
Yeah - sorry about that. See #1577 for the reversion of this. 

I think the right thing to do know is to merge #1577 and then reopen this PR. Again - so sorry about my confusion. I had two windows open simultaneously, and then acted in the wrong one.

**Comment by skoudoro** [comment]
Revert is done, can you reopen this PR @karandeepSJ?

**Pull request merged**
