### PR TITLE
NF: Convert between 4D DEC FA and 3D 24 bit representation.

### PR DESCRIPTION
**Pull request by arokem**
CC: @jchoude

### CODE REVIEW

**Comment by jchoude** [comment]
Hi @arokem 

Thanks for that! Code is ok and works, but your test doesn't pass. Could have a look?

Cheers!

**Comment by arokem** [comment]
Thanks for the poke. Should be fixed now.

**Comment by jchoude** [comment]
LGTM. Will wait until Travis is happy.

**Comment by arokem** [comment]
Seems like it's happy now.

**Comment by skoudoro** [comment]
Before merging, could you make pep8speaks happy?

**Comment by jchoude** [comment]
@skoudoro I fixed the PEP8 comments. I'm waiting on Travis just to be absolutely sure.

Is there a way to ask PEP8 speaks to rerun?

**Comment by skoudoro** [comment]
Thank you @jchoude. As you can see on top of this thread, it reruns automatically after a push and everything is good now

**Comment by skoudoro** [comment]
No, and it is not the first time. This test passed 9/10. We have to understand why the decimal precision change sometimes on this test...
I just reran the build for this PR, it should be ok.

**Comment by jchoude** [comment]
Thanks for everything.

**Pull request merged**
