### PR TITLE
Add reference to gitter chat room in the README

### PR DESCRIPTION
**Pull request by OrkoHunter**
As a new contributor, I believe it is helpful if the chat room is mentioned in the README.

### CODE REVIEW

**Comment by arokem** [comment]
I'm +1 for this.

**Comment by Garyfallidis** [comment]
+1

**Comment by Garyfallidis** [comment]
But I am not sure if it should be at the top of the Readme file. Maybe the website link should be first. Just an idea no strong feelings here.

**Comment by OrkoHunter** [comment]
@Garyfallidis What is your opinion of the current implementation?

I think we should expand the README a little bit more, with atleast a basic installation guide. Maybe something like [SymPy](https://github.com/sympy/sympy/blob/master/README.rst) or [NetworkX](https://github.com/networkx/networkx/blob/master/README.rst). If this sounds good to everyone, I may work upon it in this PR itself.

**Comment by arokem** [comment]
It could do with a small rewrite, but I would avoid too much instructions
here. Rather, you would want to direct people to the documentation.
Otherwise, we need to maintain these instructions in two different
places... Thanks!

**Comment by OrkoHunter** [comment]
@arokem Sounds fair !

**Pull request merged**
