### PR TITLE
PEP8 workflows

### PR DESCRIPTION
**Pull request by hokatvcu**
dipy/workflows/utils.py

### CODE REVIEW

**Comment by arokem** [comment]
I'm getting this on the Github UI: 

screen shot 2016-02-07 at 7 17 25 am

Did you follow the instructions in http://nipy.org/dipy/devel/gitwash/index.html?

**Comment by arokem** [comment]
Also - welcome to Dipy! Thanks for taking a look at these issues!

**Comment by hokatvcu** [comment]
I did not. I used another tutorial. Sorry I didn't know about this page. I will look over it.

**Comment by arokem** [comment]
Be sure to read through: https://github.com/nipy/dipy/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
