### PR TITLE
WIP: TEST: relaxed precision

### PR DESCRIPTION
**Pull request by Garyfallidis**
Relaxed test decimal precision after bot error reported here
http://nipy.bic.berkeley.edu/builders/dipy-py3.3-pip/builds/138/steps/shell_4/logs/stdio

### CODE REVIEW

**Comment by arokem** [comment]
This will not help here. The problem is not one of precision. The array shapes are different!

**Comment by Garyfallidis** [comment]
But the bot says : Arrays are not almost equal to 6 decimals

**Comment by Garyfallidis** [comment]
Oh yeah. You are correct. There is a shape mismatch.

**Comment by arokem** [comment]
Weird, huh? It's like move_streamlines sometimes drops a node, or EuDX
produces different numbers of nodes, depending on the affine used.

**Comment by Garyfallidis** [comment]
Which both sound impossible!

**Comment by Garyfallidis** [comment]
And we don't see them happening in other buildbots. This is strange...

**Comment by arokem** [comment]
Agreed - and this was triggered by commits entirely unrelated to this piece of code. I suspect some foul play - anything from setuptools, through pip, to the spirit of Lee Harvey Oswald.

**Comment by arokem** [comment]
Also, why is that bot not pulling the most recent version of the code? It seems that even this morning it was still pulling a version a few days old.

**Comment by Garyfallidis** [comment]
Look here at shell 3
http://nipy.bic.berkeley.edu/builders/dipy-py3.3-pip/builds/139/steps/shell_3/logs/stdio
Why is it picking up dipy 0.7.1? And not dipy 0.8.0.dev or something?

**Comment by Garyfallidis** [comment]
Closing this PR as we saw that the error appears only with old OSX versions (for example 0.6 or 0.8) and old python 3 versions. Specifically only with Python 3.3 not with Python 3.4.

**Pull request closed without merging**
