### PR TITLE
RF: Enforce integer indices

### PR DESCRIPTION
**Pull request by arokem**
So that we can wade through logs like this:
http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/640/steps/shell_9/logs/stdio

Also, a bit of PEP8.

### CODE REVIEW

**Comment by Garyfallidis** [comment]
For this one. I will have to wait for Travis to finish first.

**Comment by arokem** [comment]
yup - I've only run the test for that one module, and only on one version of python. might have unintended consequences elsewhere...

**Comment by Garyfallidis** [comment]
agreed :)

**Comment by arokem** [comment]
Seems good. I am going to go ahead and merge this, so that we can debug the buildbot that has this issue

**Pull request merged**
