### PR TITLE
[WIP] - MTMS-CSD Tutorial

### PR DESCRIPTION
**Pull request by ShreyasFadnavis**
This tutorial is also intended to delineate DIPY's ability to create pipelines.
Steps involved:
- Denoising
- Registration
- Tissue Classifier
- MCSD

Addresses #1870

### CODE REVIEW

**Comment by ShreyasFadnavis** [comment]
Hi all! I am facing some issues with the data for this example.. The only viable option that I see from the fetcher is CFIN, but needs some brain extraction on the T1.
I have a working example with the HCP data, but we do not have a fetcher for it! any suggestions would be super helpful..

**Comment by jhlegarreta** [comment]
The HCP data requires a username/pwd to be able to download it. @arokem mentioned in PR #1900 that the terms and conditions of the HCP data prevent to redistribute them, and this is one of the reasons for having the CENIR dataset in DIPY. CENIR does not have T1-weighted images, though.

I had a quick look at the [UW-Minn HCP data terms](https://www.humanconnectome.org/study/hcp-young-adult/document/wu-minn-hcp-consortium-open-access-data-use-terms), and according to point 4, data and derivatives may be re-distributed under the same data use terms. So for that part of the data may be DIPY could comply with those restrictions? May be confirmation should be asked for to UW-Minn HCP team?

If that is feasible and the data of interest for DIPY is part of the UW-Minn HCP data, then may be it could be hosted in UW's digital library, as it is the case of the CENIR data, and the corresponding fetcher could then be built?

**Comment by ShreyasFadnavis** [comment]
> The HCP data requires a username/pwd to be able to download it. @arokem mentioned in PR #1900 that the terms and conditions of the HCP data prevent to redistribute them, and this is one of the reasons for having the CENIR dataset in DIPY. CENIR does not have T1-weighted images, though.
> 
> I had a quick look at the [UW-Minn HCP data terms](https://www.humanconnectome.org/study/hcp-young-adult/document/wu-minn-hcp-consortium-open-access-data-use-terms), and according to point 4, data and derivatives may be re-distributed under the same data use terms. So for that part of the data may be DIPY could comply with those restrictions? May be confirmation should be asked for to UW-Minn HCP team?
> 
> If that is feasible and the data of interest for DIPY is part of the UW-Minn HCP data, then may be it could be hosted in UW's digital library, as it is the case of the CENIR data, and the corresponding fetcher could then be built?

Hi @jhlegarreta ! I completely agree with you. I have reached out to the HCP team and am awaiting a response. In the meantime, let me also take a look at the clauses of UW-Minn HCP ✔

**Comment by arokem** [comment]
Sorry - I believe that the HCP data is a no go for us. If I understand correctly, you can redistribute the data, but you have to put in place a mechanism for downstream users to also agree to the original terms of conditions, and we can't do that in our software. Please use the CENIR data, or some other data. Both here and in #1900.

**Comment by ShreyasFadnavis** [comment]
Hi @arokem , the issue is that CENIR does not have a T1. The next option that we have using CFIN, but is not extracted, will need something like BET + registration to do this.. Can do this, but I dont want to go outside DIPY tools for the tutorial. Does this make sense?

**Comment by jhlegarreta** [comment]
@skoudoro Sorry to chime in the middle of the release process, but I am wondering why the file added in this example is not shown in the `master` branch (either in GitHub or when fetching the branch locally). Am I missing something?

BTW, was the example left out of the [examples_index.rst](https://github.com/nipy/dipy/blob/master/doc/examples_index.rst) on purpose (e.g. needs polishing)?

**Comment by skoudoro** [comment]
Strange... 

- First, This tutorial should not be merged it is not ready at all...
- Second, I do not remember that I merged this PR, it is not even on my mailbox, 
- Third, I do not see it on master too...

Something weird happens.... Github bug?  need to investigate....

Thank you for pinging me @jhlegarreta !

**Comment by skoudoro** [comment]
I really do not know..... Somehow, this PR is linked to #1931 which I merged yesterday.  I suppose #1931 was build on the top of this branch but that's still weird, I really do not know what happens here! @arokem @Garyfallidis, @ShreyasFadnavis any idea?

**Comment by arokem** [comment]
Looks like it wasn't actually merged at all, right? So no big deal (though mysterious...). I think that @ShreyasFadnavis would need to create a new PR. Either from this branch or from a new branch.

**Comment by ShreyasFadnavis** [comment]
@jhlegarreta Thank your for pointing this out! This is scary! @arokem @skoudoro are right that this was never merged is probably a bug! Will open up a new PR for this. Nevertheless, any idea on what data set to use for this example? This tutorial needs T1 (extracted) + DWI...

**Comment by arokem** [comment]
Would a "pseudo-T1" work? You can create one from DWI data with an Anisotropic Power Map (see  e.g., https://gist.github.com/arokem/5d7441902669a4a82389)

**Comment by ShreyasFadnavis** [comment]
Thanks @arokem !! Let me this a shot... it should work I guess ✔

**Pull request merged**
