### PR TITLE
DOC: Flesh out front page example.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
well we could have just changed it from the cms as it is not a part of the documentation. 😅 

I will make a copy of it in the site.

**Comment by arokem** [comment]
Sorry - what is not part of the documentation? The front page?

I would urge you all not to use the CMS to make changes to content that we
also use version control to track (such as this page).

In general, using a CMS that doesn't work with our version control of the
docs seems like a big mistake.

**Comment by ghoshbishakh** [comment]
Sorry we had no intension of putting the docs into a database. It stays in github. I will be updating the docs in the new site soon if i get a machine to build it.

**Comment by arokem** [comment]
In particular, how do you propose adding new content, or changing existing
content? It would be imperative for this to be as open and transparent as a
Github PR. A wiki might work, but a CMS with limited user accounts is a
non-starter

**Comment by Garyfallidis** [comment]
The front page is correctly not part of the manual. And you can change that
page with a pull_request to nipy/dipy_web rather than nipy/dipy
or directly from the website.

The new website separates promotional pages from manual pages.
In that way you could have links in the intro page linking to two different
versions of the code documentation.

Ariel, because you are not buying for some reason the entire idea about the
new website I would suggest to relax on the suggestions
until we have a working version to show you and hopefully persuade you that
this is a good idea.

I would suggest you to focus on the other PRs and I will deal with the viz
and web PRs. Thanks for the advice anyway.

**Comment by ghoshbishakh** [comment]
Garyfallidis had this idea that some content needs to be changed frequently like news, publications, announcements, some images in the front page, videos and some things need to be automated like generate a gallery of tutorials etc.

So the cms is only for holding the frequently changed content and it will be keeping track of different versions of documentations that come from github.

**Comment by arokem** [comment]
On Mon, May 8, 2017 at 9:16 AM, Eleftherios Garyfallidis <
notifications@github.com> wrote:

> The front page is correctly not part of the manual. And you can change that
> page with a pull_request to nipy/dipy_web rather than nipy/dipy
> or directly from the website.
>
>
Just so I understand: what you refer to as "the manual" is the
sphinx-generated documentation. And this gets wrapped up in another
web-site that is update through a CMS? How would a user propose changes to
these web-pages? For example, if they find a typo?

The new website separates promotional pages from manual pages.
> In that way you could have links in the intro page linking to two different
> versions of the code documentation.
>
> Ariel, because you are not buying for some reason the entire idea about the
> new website I would suggest to relax on the suggestions
> until we have a working version to show you and hopefully persuade you that
> this is a good idea.
>
> I would suggest you to focus on the other PRs and I will deal with the viz
> and web PRs. Thanks for the advice anyway.
>
> Looking forward to seeing this prototype. Still, I think that it's a good
idea to have discussion on PRs and issues to hammer things out, and I don't
have any intention to stop commenting here (I don't think that anything I
said was out of line, was it?). But thank you for the advice :-)

**Comment by arokem** [comment]
On Mon, May 8, 2017 at 9:18 AM, Bishakh Ghosh <notifications@github.com>
wrote:

> Garyfallidis had this idea that some content needs to be changed
> frequently like news, publications, announcements, some images in the front
> page, videos and some things need to be automated like generate a gallery
> of tutorials etc.
>
> Agreed. That seems like a good idea. See my question above about what ends
up in each one of these categories.

> So the cms is only for holding the frequently changed content and it will
> be keeping track of different versions of documentations that come from
> github.
>
> That does seem like an improvement. Another way I have seen this done is
using the possibility of pointing Github's website generator to a
particular directory in your tree and storing static versions of
documentation from previous versions under that tree.

That way, you can also update the front page frequently (building the front
page from `master`), while maintaining stable documentation for the release
version.

**Comment by ghoshbishakh** [comment]
> How would a user propose changes to these web-pages? For example, if they find a typo?

For the manual, that is the doc, a PR in dipy repo is necessary to fix a typo.

For front page changes, video gallery changes, publication changes, and any typo in the cms pages we can login to the cms and those who have merge permission in dipy can change the content.
And for reporting purpose I think an issue is necessary. I get you point on that.

I wish I had a build system like travis ci that could maintain the docs with each commit building the docs take about 32GB of memory. For now I dont see any way of making the doc updation process seamless.

**Comment by Garyfallidis** [comment]
Here is also an answer about why dynamic and not static. We are often thinking only in terms of developers and not users. A user could very simply post some news without being a developer but still nicely advertise the project. 

In our previous experience we saw that DIPY developers (including ourselves) very rarely change and update the website especially with news. This is an effort to move away from this issue.

A dynamic website allows us to be more flexible in what we can do with the page and how we can add sections. For example, we can keep track of our own publications in one of the sections, or records some stats for grant applications etc.

Nonetheless, I think we should try it and see how it goes for a couple of years and then revisit.  But we really need to do something with our website. It definitely needed a remake.

I hope this information clarifies some of the discussion.

**Comment by Garyfallidis** [comment]
Also, let's please refrain from phrases like "big mistake" without any detailed argumentation. Working on improving our website is not a bad thing even if the dynamic website is not the correct direction we are learning a lot. Time will tell. Also, we have been working on the new website for some time so I do not understand why the urgency and emotions for changes right now. 

Finally, @ghoshbishakh had noticed high memory usage in only some of the tutorials. I believe some of those are yours @arokem so I would suggest to look into reducing the memory consumption of those tutorials. I believe we wrote issues about those some time ago I do not remember the actual issue numbers.

**Comment by arokem** [comment]
On Mon, May 8, 2017 at 6:36 PM, Eleftherios Garyfallidis <
notifications@github.com> wrote:

> Also, let's please refrain from phrases like "big mistake" without any
> detailed argumentation. Working on improving our website is not a bad thing
> even if the dynamic website is not the correct direction we are learning a
> lot. Time will tell. Also, we have been working on the new website for some
> time so I do not understand why the urgency and emotions for changes right
> now.
>
> OK - I apologize for using the extreme language about this. We could
continue the argument here (I believe there are pros and cons), but I also
realize that it's unfair to talk about this in this way, given how much
work you've already put into this. I guess I just wasn't following too
closely what was going on with the other repo, and only now starting to
realize the additional undertaking this entails. I guess we'll all become
django experts now...

> Finally, @ghoshbishakh <https://github.com/ghoshbishakh> had noticed high
> memory usage in only some of the tutorials. I believe some of those are
> yours @arokem <https://github.com/arokem> so I would suggest to look into
> reducing the memory consumption of those tutorials. I believe we wrote
> issues about those some time ago I do not remember the actual issue numbers.
>
Sure. I'll run a memory profiler tomorrow to see how much memory each
example uses.

If @ghoshbishakh could also weigh in here about which examples are
particularly memory-hungry, that would be useful. The only example-related
memory issue I could find is this one: https://github.com/nipy/d
ipy/issues/1224. I think that this should be somewhat alleviated with the
new data-set that was added over on https://github.com/nipy/dipy/pull/1226.
I looked over all the other issues and there don't seem to be any others
that are related to memory in the examples. But like I said - I can try to
profile that tomorrow in more detail, so we know where to focus.

**Comment by arokem** [comment]
This is not going to be in the new website. Closing

**Pull request closed without merging**
