### PR TITLE
workflows : warn user for strange b0 threshold 

### PR DESCRIPTION
**Pull request by skoudoro**
I just added a warning when b0 threshold is smaller than all b-values.

I had to duplicate the code many times. It is not the first time. This means a new PR is needed to create a parent class (ReconstWorkflow) and avoid the redundancy.

### CODE REVIEW

**Comment by arokem** [comment]
Nice. Any chance to get a test of this behavior?

**Comment by skoudoro** [comment]
- What is the good way to test logging module @arokem?

- When we enter into this specific condition, an error is always generated later in the code. It seems I should convert this warning into an error. What do you think @arokem @Garyfallidis?

**Comment by skoudoro** [comment]
I added the test so this one is ready to go @arokem

**Comment by skoudoro** [comment]
Hi @arokem, can you check this one?

Thank you

**Comment by arokem** [comment]
Yep. Ready to go!

**Comment by skoudoro** [comment]
Thanks!

**Pull request merged**
