### PR TITLE
BF: Normalization of GQI2 `gqi_vector`.

### PR DESCRIPTION
**Pull request by arokem**
A long overdue fix, , with thanks to @qytian for fixing this and reminding me to
put in this PR on his behalf.

Follow-up of this conversation: http://mail.scipy.org/pipermail/nipy-devel/2013-November/009574.html

### CODE REVIEW

**Comment by Garyfallidis** [comment]
Hey thanks @qytian and @arokem for looking at this. Can you show as the improved ODFs in a before after figure for a 60 degrees crossing for example?

**Comment by arokem** [comment]
On `master`:

master

One this branch:
qgi-norm-fix

**Comment by arokem** [comment]
http://nbviewer.ipython.org/gist/arokem/f92967b718ead8fa494b

**Comment by Garyfallidis** [comment]
Can you generate the same 2 figures but with sampling_length = 3?

**Comment by arokem** [comment]
master

qgi-norm-fix

**Comment by Garyfallidis** [comment]
Aha!

**Comment by Garyfallidis** [comment]
Okay thank you. I asked for this so we can have a reference on the change of sampling_length after the new pi correction. 

Thank you both :)

**Comment by qytian** [comment]
The abstract "Deconvolution enhanced Generalized Q-Sampling 2 and DSI deconvolution" recommends an integration length lamda between 2 and 3. I am not sure whether here includes the "pi" constant, i.e. [2, 3] / pi.

**Comment by Garyfallidis** [comment]
Yes, because it was using the old code (without your fix). @arokem and @qytian would you mind adding this information to the docstring of the function? I mean say that range of the sampling length has changed? We need also to write this in the api_changes.rst file. Thank you again.

**Comment by arokem** [comment]
Yeah - no problem. @qytian and I will work on another PR for that.

**Comment by samuelstjean** [comment]
Regarding the second screenshot, is that supposed to happen? You seem to have reversed the orientation of the crossings to 90 degress on that stick figure, while it was more like 60 degrees before.

**Comment by Garyfallidis** [comment]
Yeah, it's correct. It is the same as sampling from outside the PDF grid in DSI. Your values will not be correct or very small (in the case of GQI2)  and then you may start seeing effects of the sampling sphere in the results.

**Pull request merged**
