### PR TITLE
Updated copyright to 2016

### PR DESCRIPTION
**Pull request by Famguy**

### CODE REVIEW

**Comment by arokem** [comment]
Happy new year! :tada:

**Comment by Famguy** [comment]
Happy New Year to you too @arokem ! :) 
I was actually looking for an opportunity to contribute to. If there could be anything that I could help in, please guide me to it. Thanks!

**Comment by arokem** [comment]
How about this one? https://github.com/nipy/dipy/issues/802

**Comment by arokem** [comment]
Thank you!

**Pull request merged**
