### PR TITLE
Remove deprecated voxel_size from seed_from_mask

### PR DESCRIPTION
**Pull request by skoudoro**
everything in the title 😄!

### CODE REVIEW

**Comment by arokem** [comment]
Was there no test to catch that?

**Comment by skoudoro** [comment]
> Was there no test to catch that?

No, All tests and tutorials were using `affine` parameter and not the deprecated `voxel_size`

**Comment by frheault** [comment]
There will be a conflict, I have an incoming PR that remaster the whole dipy.tracking.utils to force the affine in most functions. It also change the docstring so the affine description is the same everywhere, delete the functions we agreed upon (confusing and/or not use anywhere)

**Comment by skoudoro** [comment]
ok @frheault, I will just close this PR as soon as you create your PR.

I want to create a PR for removing `save_trk` from `dipy.io.trackvis`. Are you working on this too?

**Comment by frheault** [comment]
I'm not, you can delete the whole file 😉

**Pull request closed without merging**
