### PR TITLE
Optimize dipy.align.reslice

### PR DESCRIPTION
**Pull request by dimrozakis**
- Using a 1D transformation matrix instead of a 2D diagonal matrix reduces computation time.
- Using the `output` argument in `affine_transform` reduces memory usage.

### CODE REVIEW

**Comment by arokem** [comment]
Looks great to me. If someone else could take a look that would be great. Otherwise, if no one has any comments, I can merge this towards the end of the week. Thanks!

**Comment by dimrozakis** [comment]
In https://github.com/tomotech/dipy/commit/7f7e8a74e9b6395124a00fac095ca2751e8f6d51 I added the option to use `multiprocessing.Pool` in `reslice`. Should I push the commit into this branch as well?

**Comment by Garyfallidis** [comment]
Good idea @dimrozakis. Use ``num_processes`` as a variable name rather than ``mp``. We usually use ``num_processes`` or ``nbr_processes``  when using multiprocessing and ``num_threads`` when using multithreading.

**Comment by dimrozakis** [comment]
@arokem I just fixed the missing space issue in the `num_processes` definition of `dipy.align.reslice` docstring according to your comment

**Comment by arokem** [comment]
Thanks! I will wait for travis to give this a run through, and then merge...

**Comment by arokem** [comment]
I just noticed that test coverage here seems rather spotty (63% for the module). Any chance you could do something about that? Thanks!

**Comment by dimrozakis** [comment]
@arokem I added more tests, now coverage is at 98%

The 8th test case, the one with `python-vtk` fails. I have no idea why. It failed on the previous commit as well, which simply added a space character, so it must involve something merged to master since this branch was forked?

**Comment by arokem** [comment]
Thanks. That's fantastic!

The VTK machine failure is a known (and rather hard!) issue. We'll sort it
out, but maybe not on this PR...

**Pull request merged**
