### PR TITLE
BF: use MAM distance when that is requested.

### PR DESCRIPTION
**Pull request by arokem**
Also, fixes the docstring to the used default.

Addresses https://github.com/nipy/dipy/issues/1982

### CODE REVIEW

**Comment by arokem** [comment]
The CI failure seems unrelated, so I restarted that job.

**Comment by skoudoro** [comment]
> The CI failure seems unrelated, so I restarted that job

Note: Cool and really useful feature not available on Azure yet ...

Thank you, merging

**Comment by arokem** [comment]
> Note: Cool and really useful feature not available on Azure yet ...

You  can probably still kick off an entire new round of CI by amending your commit message and force pushing?

**Comment by skoudoro** [comment]
Yes, of course,  you can restart the whole pr via a button or an empty commit.

**Pull request merged**
