### PR TITLE
Typo in release notes

### PR DESCRIPTION
**Pull request by arokem**
Sorry for only noticing this now. I do believe @wasserth spells his name with a "K": https://www.dkfz.de/en/mic/team/people/Jakob_Wasserthal.html

### CODE REVIEW

**Comment by skoudoro** [comment]
good catch! Sorry about that...

Can you correct it on `AUTHOR` file and `.mailmap` file?

**Comment by wasserth** [comment]
With "k" is the correct spelling. Thanks for spotting that typo ;).

**Comment by skoudoro** [comment]
Can you update AUTHOR file and .mailmap file too @arokem?

**Comment by arokem** [comment]
done!

**Comment by skoudoro** [comment]
Great, Thank you! merging!

**Pull request merged**
