### PR TITLE
Fix for Python 3 in io.dpy

### PR DESCRIPTION
**Pull request by ghoshbishakh**

### CODE REVIEW

**Comment by arokem** [comment]
Thanks for doing this! Could you please write a test that fails without this fix?

**Comment by ghoshbishakh** [comment]
@arokem sure but can you guide me a bit where to write it. As this is a tutorial.

**Comment by arokem** [comment]
Here: https://github.com/nipy/dipy/blob/master/dipy/io/tests/test_dpy.py

**Comment by ghoshbishakh** [comment]
@arokem Actually without the changes in this PR, the test already fails:

```
bishakh@bisu-arch ~/projects/dipy/dipy/io (git)-[master] % python3 -m "nose"   
..E..
======================================================================
ERROR: dipy.io.tests.test_dpy.test_dpy
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3.5/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/home/bishakh/projects/dipy/dipy/io/tests/test_dpy.py", line 24, in test_dpy
    dpw = Dpy(fname, 'w')
  File "/home/bishakh/projects/dipy/dipy/io/dpy.py", line 70, in __init__
    ['0.0.1'], 'Dpy Version Number')
  File "/usr/lib/python3.5/site-packages/tables/_past.py", line 35, in oldfunc
    return obj(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/tables/file.py", line 1152, in create_array
    obj=obj, title=title, byteorder=byteorder)
  File "/usr/lib/python3.5/site-packages/tables/array.py", line 188, in __init__
    byteorder, _log)
  File "/usr/lib/python3.5/site-packages/tables/leaf.py", line 262, in __init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "/usr/lib/python3.5/site-packages/tables/node.py", line 267, in __init__
    self._v_objectid = self._g_create()
  File "/usr/lib/python3.5/site-packages/tables/array.py", line 205, in _g_create
    raise TypeError("Array objects cannot currently deal with void, "
TypeError: Array objects cannot currently deal with void, unicode or object arrays

----------------------------------------------------------------------
Ran 5 tests in 0.016s

FAILED (errors=1)
Closing remaining open files:test.bin...done
```

**Comment by ghoshbishakh** [comment]
@arokem what version of pytables is travis using in the tests?

**Comment by ghoshbishakh** [comment]
@arokem So the problem is with the `@iftables` decorator. Travis is skipping this test as pytables is not installed in travis. But why it is done like this to skip a test deliberately when pyables is not installed?

**Comment by arokem** [comment]
It used to be fairly complicated to install, so I think this is here so that people aren't obliged to install pytables. 

Let's see if we can get it in: https://github.com/nipy/dipy/pull/1101

**Comment by ghoshbishakh** [comment]
@arokem so pr #1101 should be failing in tests. And then once that is merged this pr will be passing the tests right? Then let me know what should be my next steps when that is merged. This is quite interesting to see how TDD works :smiley:

**Comment by arokem** [comment]
Exactly, once we sort that one out (actually #1102 now), you should be able
to rebase on master, and we should see whether this fix works.

**Comment by arokem** [comment]
I think this works! 

https://travis-ci.org/nipy/dipy/jobs/148274744#L1951
https://travis-ci.org/nipy/dipy/jobs/148274745#L1971

**Pull request merged**
