### PR TITLE
changed samuel st-jean email to the usherbrooke one

### PR DESCRIPTION
**Pull request by samuelstjean**
More professional than a gmail address.

### CODE REVIEW

**Comment by jchoude** [comment]
Which email address do you use for your commits? I would guess your gmail one... It's probably easier to keep the same, for easiness of mapping later on, but I'll let @Garyfallidis or others decide.

**Comment by samuelstjean** [comment]
Apparently I use this one also for commiting stuff

stjs2902 ~ $ [~] git config --global user.email
<snip>@usherbrooke.ca -> you get the idea

**Comment by arokem** [comment]
Hey @samuelstjean - sorry for the delay (HBM, life...). Seems fine to me. There are a few people who commit with a few different email addresses. This is documented in the `.mailmap` file as well, so please change it there as well.

**Comment by samuelstjean** [comment]
Does .mailmap serves a purpose or it is not updated frequently? There seems to be few email addresses  in there, and mine is not there, should I add it?

**Comment by matthew-brett** [comment]
Checkout https://www.google.com/?gws_rd=ssl#q=mailmap 

`.mailmap` serves to identify two or more email addresses and commit names with the same person.  You'll only see an address there if someone commits with more than one name / email pair.

**Comment by samuelstjean** [comment]
Oh ok, I did not know that. Anyway, I don't fall in thta usecase as my commit email is the one I am changing for in this current PR, the gmail one has never been used (yet, it'll probably come into usage when my academic one expire if I don't find another one by then).

**Comment by arokem** [comment]
According to 'git -se', you've used the following emails to make commits:

Samuel St-Jean <Samuel.St-Jean@usherbrooke.ca>

Samuel St-Jean <stjeansam@gmail.com>
Samuel St-Jean <qekchose@gmail.com>

It would be good to have all of them in that .mailmap file.

**Comment by samuelstjean** [comment]
Isn't that a garanteed recipe for tons of spam tough to have clear text emails everywhere online?

**Comment by arokem** [comment]
Spam is a given.

**Pull request merged**
