### PR TITLE
Mapmri workflow rebased

### PR DESCRIPTION
**Pull request by arokem**
I believe this is a rebased version of #1388

### CODE REVIEW

**Comment by skoudoro** [comment]
Hi @arokem, Thanks for doing this! Can you rename `dipy_mapmri` to `dipy_fit_mapmri`. I believed the last version was #1395 and not #1388 but I need to check the difference.

**Comment by arokem** [comment]
Script renamed. Still need to figure out #1433...

**Comment by skoudoro** [comment]
hi @arokem, can you rebase? it should be good after that

**Comment by arokem** [comment]
Yep. Done!

**Comment by skoudoro** [comment]
Thank @arokem and @aarya22! merging mapmri workflow!

**Comment by arokem** [comment]
Thanks! Congratulations @aarya22 on a nice contribution! 💯🥇🎆 

cc @francopestilli

**Pull request merged**
