### PR TITLE
changed window.record() to a large value

### PR DESCRIPTION
**Pull request by ShreyasFadnavis**

### CODE REVIEW

**Comment by ShreyasFadnavis** [comment]
Maybe I misunderstood?

**Comment by karandeepSJ** [comment]
Did you try the 5000x5000 image on Linux? window.record() works fine on Linux. The problem is on Windows

**Comment by ShreyasFadnavis** [comment]
Yes, I did.. It works fine on my Windows PC!

**Comment by jchoude** [comment]
Is this for issue #1420? IF so, I don't think that's the fix that @dmreagan intended... This hardcoded value is not better, and might fail depending on the driver and GPU of the user. I guess that @dmreagan wanted something that could check that max resolution supported by the user's machine and work within those boundaries.

**Comment by dmreagan** [comment]
@jchoude is correct that I wasn't looking for someone to change the values in the examples. I was hoping the underlying VTK functionality just wasn't being configured correctly for the case described in #1420. But it is good feedback from @ShreyasFadnavis and @karandeepSJ that large resolutions work correctly on your systems. I think it's probaby best to close this PR and continue the discussion in the issue.

**Pull request closed without merging**
