### PR TITLE
WIP: Dki

### PR DESCRIPTION
**Pull request by arokem**
This is still WIP, but I think that I am about ready for others to also start taking a look at this. 

I am relying mostly on these two papers for the implementation details: 

    [1] Lu, H, Jensen, JH, Ramani, A, Helpern, JA (2006). Three-dimensional
    characterization of non-gaussian water diffusion in  humans using diffusion
    kurtosis imaging. NMR in Biomedicine 19: 236-247

    [2] Jensen, JH and Helpern JA (2010). MRI quantification of non-Gaussian
    water diffusion by kurtosis analysis. NMR in Biomedicine 23: 698-710.

However, I am trying to generalize this to cases in which measurements were conducted in different directions in the different b values. Not sure if that's legit.

### CODE REVIEW

**Comment by Garyfallidis** [comment]
@arokem Would it be possible to rebase this PR? I think @Chantal and the DKI team will try to build on top of it or use some parts. So, it would be nice if it could run as it is now with the latest version. If you  think this is a bad idea and they should make their own PR from scratch please say so.  Thx.

**Comment by arokem** [comment]
I'll give it a try and report back.

**Comment by arokem** [comment]
I've rebased on master. I ended up merging in dti and dki in from master, because this ended up behind `master` for some reason: I used `--theirs` to resolve the conflicts on these files, but it seems that this got interpreted as resolving towards the `dki` branch. Any ideas on how to make the last two commits nicer in the history?

**Comment by hassemlal** [comment]
Hi,
It looks like the pull request #664 supersedes this request, maybe it should be closed?

**Comment by arokem** [comment]
Good call. Been meaning to do this.

**Comment by arokem** [comment]
Closing, because this was superseded by #664

**Pull request closed without merging**
