### PR TITLE
DOC: TensorModel.__init__ docstring.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by jchoude** [comment]
Seems good to me. Can merge in a few days if no one says anything.

**Comment by jchoude** [comment]
No one wants to chime in? I know this is a benign change.

**Comment by arokem** [comment]
🚢

**Comment by jchoude** [comment]
Thanks @arokem (and yeah! for the first PR that I merge)

**Comment by arokem** [comment]
Congratulations! Here's to many more!

**Pull request merged**
