### PR TITLE
NF: Added support to colorize each line points indivdually

### PR DESCRIPTION
**Pull request by gauvinalexandre**

### CODE REVIEW

**Comment by MarcCote** [comment]
LGTM

**Comment by gauvinalexandre** [comment]
Half a day to find those 5 lines. Damn.

**Comment by arokem** [comment]
I am not sure what's going on here, but it looks like @MarcCote gave this the thumbs-up months ago. Unless someone objects, I can merge this early next week.

**Comment by gauvinalexandre** [comment]
Thank you!

**Comment by MarcCote** [comment]
@gauvinalexandre if you could add some information about this new feature in the docstring that would be nice. Here is a suggestion: "If an array (K, 3) is given, where K is the number of points of all lines then every point is colored with a different RGB color."

I remembered testing it and it was working fine. I should have merged it a while back, so early next week sounds good.

**Comment by gauvinalexandre** [comment]
Thanks @MarcCote ! I would add some info, but unfortunately I don't have much time to go back in the code and explain the use cases and show examples... If this is necessary before the merge, maybe we should wait... I'll add this to my short term todo list.

**Comment by arokem** [comment]
No need for examples here, in my opinion (though we would really welcome
that, in a separate PR). Just the addition of that sentence into the
docstring.

**Comment by arokem** [comment]
I second the suggestion to document this! I'll wait for that to come in and
then merge.

**Comment by MarcCote** [comment]
@gauvinalexandre just merge this PR that I've made on top of your branch: https://github.com/gauvinalexandre/dipy/pull/1

**Comment by gauvinalexandre** [comment]
Thanks @MarcCote !

**Comment by arokem** [comment]
I'm going to ignore the codecov weirdness here, and go ahead with the merge

**Comment by arokem** [comment]
Thanks @gauvinalexandre !

**Comment by MarcCote** [comment]
Probably a rebase was needed since we drop the coverage of benchmark files.

**Comment by arokem** [comment]
That's probably it. Looks like it merged cleanly anyway...

**Pull request merged**
