### PR TITLE
Fix pep8 in workflows

### LINKED ISSUE #891: PEP8 in workflows
dipy/workflows/base.py:7:1: E302 expected 2 blank lines, found 1
dipy/workflows/base.py:50:80: E501 line too long (84 > 79 characters)
dipy/workflows/base.py:51:80: E501 line too long (85 > 79 characters)
dipy/workflows/base.py:52:80: E501 line too long (82 > 79 characters)
dipy/workflows/base.py:91:16: E111 indentation is not a multiple of four
dipy/workflows/base.py:98:18: E111 indentation is not a multiple of four
dipy/workflows/base.py:141:1: W391 blank line at end of file
dipy/workflows/docstring_parser.py:4:80: E501 line too long (90 > 79 characters)
dipy/workflows/docstring_parser.py:36:1: E302 expected 2 blank lines, found 1
dipy/workflows/docstring_parser.py:48:27: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:51:41: E261 at least two spaces before inline comment
dipy/workflows/docstring_parser.py:59:20: E261 at least two spaces before inline comment
dipy/workflows/docstring_parser.py:91:9: E301 expected 1 blank line, found 0
dipy/workflows/docstring_parser.py:100:18: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:109:1: E302 expected 2 blank lines, found 1
dipy/workflows/docstring_parser.py:113:1: E302 expected 2 blank lines, found 1
dipy/workflows/docstring_parser.py:140:25: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:143:25: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:143:29: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:160:39: E261 at least two spaces before inline comment
dipy/workflows/docstring_parser.py:160:40: E262 inline comment should start with '# '
dipy/workflows/docstring_parser.py:163:20: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:166:14: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:167:28: E701 multiple statements on one line (colon)
dipy/workflows/docstring_parser.py:169:14: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:170:28: E701 multiple statements on one line (colon)
dipy/workflows/docstring_parser.py:178:47: E261 at least two spaces before inline comment
dipy/workflows/docstring_parser.py:190:38: E261 at least two spaces before inline comment
dipy/workflows/docstring_parser.py:197:31: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:210:36: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:210:45: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:249:32: E701 multiple statements on one line (colon)
dipy/workflows/docstring_parser.py:318:80: E501 line too long (80 > 79 characters)
dipy/workflows/docstring_parser.py:319:80: E501 line too long (81 > 79 characters)
dipy/workflows/docstring_parser.py:342:50: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:362:22: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:362:33: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:380:32: E701 multiple statements on one line (colon)
dipy/workflows/docstring_parser.py:407:52: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:424:26: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:424:39: E231 missing whitespace after ','
dipy/workflows/docstring_parser.py:429:30: W292 no newline at end of file
dipy/workflows/segment.py:80:80: E501 line too long (84 > 79 characters)
dipy/workflows/utils.py:4:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/__init__.py:3:11: W292 no newline at end of file
dipy/workflows/tests/test_docstring_parser.py:4:80: E501 line too long (90 > 79 characters)
dipy/workflows/tests/test_docstring_parser.py:33:11: E401 multiple imports on one line
dipy/workflows/tests/test_docstring_parser.py:39:5: E731 do not assign a lambda expression, use a def
dipy/workflows/tests/test_docstring_parser.py:41:5: E731 do not assign a lambda expression, use a def
dipy/workflows/tests/test_docstring_parser.py:107:80: E501 line too long (80 > 79 characters)
dipy/workflows/tests/test_docstring_parser.py:172:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:176:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:179:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:181:26: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:181:28: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:181:61: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:181:67: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:188:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:190:26: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:190:28: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:195:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:209:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:214:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:218:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:222:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:227:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:227:37: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:232:10: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:236:36: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:236:41: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:237:1: E302 expected 2 blank lines, found 0
dipy/workflows/tests/test_docstring_parser.py:242:1: E128 continuation line under-indented for visual indent
dipy/workflows/tests/test_docstring_parser.py:351:1: E303 too many blank lines (3)
dipy/workflows/tests/test_docstring_parser.py:362:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:386:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:388:9: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:388:11: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:389:22: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:390:22: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:392:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:394:9: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:394:11: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:395:22: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:396:22: E231 missing whitespace after ','
dipy/workflows/tests/test_docstring_parser.py:398:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:400:5: E122 continuation line missing indentation or outdented
dipy/workflows/tests/test_docstring_parser.py:450:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_docstring_parser.py:456:5: E122 continuation line missing indentation or outdented
dipy/workflows/tests/test_docstring_parser.py:497:15: W292 no newline at end of file
dipy/workflows/tests/test_iap.py:5:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_iap.py:32:12: E127 continuation line over-indented for visual indent
dipy/workflows/tests/test_iap.py:33:12: E127 continuation line over-indented for visual indent
dipy/workflows/tests/test_iap.py:65:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_iap.py:88:1: E302 expected 2 blank lines, found 1
dipy/workflows/tests/test_utils.py:6:1: E302 expected 2 blank lines, found 1

### PR DESCRIPTION
**Pull request by ghoshbishakh**
fixes #891

### CODE REVIEW

**Comment by arokem** [comment]
This one's already being worked on in #896

**Comment by ghoshbishakh** [comment]
oh ok :+1:

**Comment by ghoshbishakh** [comment]
@arokem the other PR is closed I saw. So will that be reopened?

**Comment by hokatvcu** [comment]
I closed the other one. If you have a completed branch, then you are welcomed to take over.

**Comment by ghoshbishakh** [comment]
@arokem you may take a look

**Comment by arokem** [comment]
Looks good. Merging.

**Pull request merged**
