### PR TITLE
Offscreen is False for test_slicer

### PR DESCRIPTION
**Pull request by Garyfallidis**
Depending on the hardware/software version of the bot sometimes the snapshot cannot work in stealthmode. For now I am changing for this test to offscreen=False. Hopefully this will resolve the current fail in master and in the future we can figure out how to stabilize xvfb.

### CODE REVIEW

**Comment by arokem** [comment]
Fingers crossed!

**Comment by Garyfallidis** [comment]
Let see how it goes. I think a lot of these issues will be solved when move the bots to VTK 6.... Well, maybe...

**Comment by Garyfallidis** [comment]
@arokem this is now passing. I had to skip the slicer test in VTK 5.

**Comment by Garyfallidis** [comment]
Good idea I can try to make it skip on Travis and vtk 5.

**Comment by arokem** [comment]
Yeah - you'll know you're on travis with this check: https://github.com/nipy/dipy/blob/master/dipy/testing/decorators.py#L54

**Comment by Garyfallidis** [comment]
Can you double check that this test still fails in darwin?

**Comment by Garyfallidis** [comment]
I have now offscreen=False so that should work on Darwin.

**Comment by arokem** [comment]
You're right! That one does actually pass. But this one is failing under vtk 5 on darwin:
```
======================================================================
FAIL: dipy.viz.tests.test_fvtk_widgets.test_text_widget
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arokem/anaconda/envs/py2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/arokem/anaconda/envs/py2/lib/python2.7/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/Users/arokem/source/dipy/dipy/testing/decorators.py", line 63, in test_with_xvfb
    my_test()
  File "/Users/arokem/anaconda/envs/py2/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/Users/arokem/anaconda/envs/py2/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/Users/arokem/source/dipy/dipy/viz/tests/test_fvtk_widgets.py", line 180, in test_text_widget
    npt.assert_equal(report.objects, 3)
  File "/Users/arokem/anaconda/envs/py2/lib/python2.7/site-packages/numpy/testing/utils.py", line 354, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 492
 DESIRED: 3
```

Should we skip it on darwin?

**Comment by Garyfallidis** [comment]
No because it is fine with some darwin machines. But I can force it to go offscreen=False which may resolve the problem. You can try it too.

**Comment by arokem** [comment]
That actually worries me a bit. What's different about these machines? Are these other darwin machines on which this test passes also running vtk5 installed through conda?

We might not be able to get to the bottom of this, but it is a bit disturbing.

**Comment by Garyfallidis** [comment]
Yes, there were two darwin machines passing those tests.

**Comment by Garyfallidis** [comment]
Look what I understand right now is that with Darwin machines offscreen=True (in snapshot) is not working sometimes. And that is normal in VTK 5 as I said before the snapshot was made initially to run the visual tests in Linux machines for VTK 5 and hopefully support more OS's with VTK 6. Does this explanation help?

**Comment by arokem** [comment]
Where do I put the `offscreen=False`?

**Comment by arokem** [comment]
What's different about those two laptops? 

I am running OS 10.11.1 
Python 2.7.10 from Anaconda 

vtk.vtkVersion.GetVTKMajorVersion(): 5
Version.GetVTKBuildVersion(): 1
vtk.vtkVersion.GetVTKMinorVersion(): 10
vtk.vtkVersion.GetVTKSourceVersion(): 'vtk version 5.10.1'
vtk.vtkVersion.GetVTKVersion(): '5.10.1'

np.__version__ : '1.10.1'

Is it any different from the machines on which this does pass?

**Comment by Garyfallidis** [comment]
window.snapshot

**Comment by arokem** [comment]
It's set to be `offscreen=True` per default: 

https://github.com/nipy/dipy/blob/master/dipy/viz/window.py#L661

**Comment by arokem** [comment]
So - I should set that to False?

**Comment by arokem** [comment]
It fails in the same way when I do that.

**Comment by Garyfallidis** [comment]
Same vtk different hardware. More recent hardware notebooks. @daducci what version is you macbook and what graphics card does it have?

**Comment by Garyfallidis** [comment]
Okay this is unexpected!

**Comment by arokem** [comment]
Ugh. Hardware differences.

**Comment by Garyfallidis** [comment]
Do you get the same issue with VTK 6?

**Comment by arokem** [comment]
Nope. VTK6 seems to fix it.

**Comment by arokem** [comment]
Let's take this conversation to gitter!

**Comment by Garyfallidis** [comment]
OKay so most likely this is a VTK 5 issue on some Mac machines.

**Comment by Garyfallidis** [comment]
Can you try to run window.record and see if the PNG file comes out correctly?

**Comment by daducci** [comment]
I recently upgraded to "El Capitan" (OSX 10.11)and the video card is listed as "Intel Iris 1536 MB". @Garyfallidis, do you need more info?

**Comment by arokem** [comment]
Yeah - I have both of these as well (El-Capitan, and Intel Iris Graphics
6100 1536 MB)

@daducci: how did you install vtk on your mac? I installed with Anaconda.
Did you get yours through homebrew, or something like that?

On Sun, Nov 8, 2015 at 2:52 PM, Alessandro Daducci <notifications@github.com

**Comment by daducci** [comment]
Hi @arokem ,
to be honest, I do not remember.. Is that a way to check it a posteriori? I guess it came with Anaconda as well.

**Comment by arokem** [comment]
If you have anaconda it's likely it's from there.

You could check with:

    import vtk
    vtk.__file__

On my machine it looks like this:
`'/Users/arokem/anaconda/envs/py2/lib/python2.7/site-packages/vtk/__init__.pyc'`

On Sun, Nov 8, 2015 at 3:10 PM, Alessandro Daducci <notifications@github.com

**Comment by daducci** [comment]
Yes, I confirm:
`'/Users/ale/anaconda/lib/python2.7/site-packages/vtk/__init__.pyc'`

**Comment by arokem** [comment]
Could you please run `pip freeze` and paste the whole thing here?

Just confirming: tests all run without a hitch for you on current dipy
master?

On Sun, Nov 8, 2015 at 5:13 PM, Alessandro Daducci <notifications@github.com

**Comment by daducci** [comment]
For the tests, you should ask @Garyfallidis: I had lent him my laptop and actually I don't know what he tested in detail. Btw, here is the output from `pip freeze`:
```
abstract-rendering==0.5.1
alabaster==0.7.6
amico==1.0
appnope==0.1.0
argcomplete==0.8.1
astropy==1.0.3
atom==0.3.9
autopep8==1.1.1
Babel==2.1.1
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.3.2
binstar==0.7.1
bitarray==0.8.1
blaze==0.6.3
blz==0.6.2
bokeh==0.6.1
boto==2.32.1
casuarius==1.1
cdecimal==2.3
certifi==14.5.14
cffi==0.8.6
chaco==4.4.1
colorama==0.3.1
commit==1.0
conda==3.18.3
conda-build==1.8.2
conda-env==2.4.4
configobj==5.0.6
cryptography==0.5.4
cycler==0.9.0
Cython==0.21
cytoolz==0.7.0
DataShape==0.3.0
decorator==4.0.4
docutils==0.12
enable==4.3.0
enaml==0.9.8
Flask==0.10.1
future==0.13.1
futures==2.1.6
gevent==1.0.1
gevent-websocket==0.9.3
glueviz==0.5.1
greenlet==0.4.4
grin==1.2.1
h5py==2.3.1
ipykernel==4.1.1
ipython==4.0.0
ipython-genutils==0.1.0
itsdangerous==0.24
jdcal==1.0
jedi==0.9.0
Jinja2==2.8
jsonschema==2.4.0
jupyter-client==4.1.1
jupyter-core==4.0.6
kiwisolver==0.1.3
llvmpy==0.12.7
lxml==3.4.0
MarkupSafe==0.23
matplotlib==1.4.0
mistune==0.7.1
mock==1.0.1
multipledispatch==0.4.7
nbconvert==4.0.0
nbformat==4.0.1
networkx==1.9.1
nibabel==2.0.0
nltk==3.0.0
nose==1.3.4
numba==0.14.0
numexpr==2.3.1
numpy==1.9.3
openpyxl==1.8.5
pandas==0.16.2
path.py==0.0.0
patsy==0.3.0
pep8==1.6.2
pexpect==3.3
pickleshare==0.5
PIL==1.1.7
Pillow==2.9.0
ply==3.4
psutil==3.2.2
ptyprocess==0.4
py==1.4.25
PyAudio==0.2.7
pycosat==0.6.1
pycparser==2.10
pycrypto==2.6.1
pycurl==7.19.5
pyface==4.4.0
pyflakes==1.0.0
Pygments==2.0.2
PyInstaller==3.0
pyOpenSSL==0.14
pyparsing==2.0.1
pytest==2.6.3
python-dateutil==2.4.1
pytz==2015.7
PyYAML==3.11
pyzmq==14.7.0
qtconsole==4.1.0
redis==2.9.1
requests==2.8.1
rope==0.9.4
runipy==0.1.1
scikit-image==0.11.3
scikit-learn==0.15.2
scipy==0.15.1
simplegeneric==0.8.1
six==1.10.0
snowballstemmer==1.2.0
sockjs-tornado==1.0.1
spams==2.5
Sphinx==1.3.1
sphinx-rtd-theme==0.1.7
spyder==2.3.7
SQLAlchemy==0.9.7
statsmodels==0.5.0
sympy==0.7.5
tables==3.1.1
terminado==0.5
toolz==0.7.0
tornado==4.2.1
tractconverter==0.7.5.dev0
traitlets==4.0.0
traits==4.4.0
traitsui==4.4.0
ujson==1.33
unicodecsv==0.9.4
VTK==5.10.1
Werkzeug==0.9.6
wheel==0.26.0
xlrd==0.9.3
XlsxWriter==0.5.7
xlwt==0.7.5
 ```

**Comment by arokem** [comment]
Thanks. I am still not sure why this works on your machine, but not mine.

**Pull request merged**
