### PR TITLE
DOC: Improve the `doc/README` file contents

### PR DESCRIPTION
**Pull request by jhlegarreta**
Improve the `doc/README` file contents:
- Match the explained folder list with the actual folders in the `doc`
  folder.
- Improve markup.
- Improve wording.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Will need to be rebased on `master` #1979 gets merged to fix the conflict.

**Comment by skoudoro** [comment]
Thank you @jhlegarreta.

Why does the file extension need to be on a different PR? I would recommend to close #1979 and do it here

**Comment by jhlegarreta** [comment]
> Why does the file extension need to be on a different PR? I would recommend to close #1979 and do it here

It does not to be. IMHO makes the purpose of the PRs clearer.

**Comment by jhlegarreta** [comment]
Rebased on `master` after #1979 has been merged.

**Comment by jhlegarreta** [comment]
@skoudoro This is ready to be merged.

**Pull request merged**
