### PR TITLE
Preloader element for viz.ui

### PR DESCRIPTION
**Pull request by karandeepSJ**
This PR adds an animated element to `viz.ui`, a Preloader. It consists of three concentric, multi-colored arcs rotating about their centre. A repeating timer is used to call the rotation callback whenever the timer ends and restarts.
The following script can be used to run it:
```
import dipy.viz.ui as ui
import dipy.viz.window as window
loader = ui.Preloader(outer_radius=100, center=(300, 300))
sm=window.ShowManager(size=(600, 600))
sm.initialize()
sm.iren.CreateRepeatingTimer(10)
loader.add_callback(sm.iren, 'TimerEvent', loader.rotation_callback)
sm.ren.add(loader)
sm.start()
``` 

loader

### CODE REVIEW

**Comment by arokem** [comment]
So pretty! I could watch that forever ❤️

**Comment by dmreagan** [comment]
Looks like there's an error with `test_ui_preloader` on Travis. Could be a VTK 5.8 problem.

**Comment by skoudoro** [comment]
many chances. We have to take a decision on this problem (VTK version).

**Comment by karandeepSJ** [comment]
Yeah this is a version problem. `vtkArcSource` did not have the polar form of coordinates in older versions.

**Comment by Garyfallidis** [comment]
Agree with all 3. And definitely an image will be much easier to change. More generic.

**Comment by karandeepSJ** [comment]
I can create a function `initialize_loader` that takes the `ShowManager` object and executes the three commands:
```
sm.initialize()
sm.iren.CreateRepeatingTimer(10)
loader.add_callback(sm.iren, 'TimerEvent', loader.rotation_callback)
```

**Comment by skoudoro** [comment]
Closing. This PR was moved to https://github.com/fury-gl/fury/pull/19

**Pull request closed without merging**
