### PR TITLE
Removes the appveyor configuration file.

### PR DESCRIPTION
**Pull request by arokem**
Following up on the conversation on https://github.com/nipy/dipy/pull/2008#issuecomment-566191117, I want to check whether appveyor will build this branch, considering it doesn't have an appveyor config file.

### CODE REVIEW

**Comment by arokem** [comment]
Blergh. Looks like appveyor is trying to build this. Don't have time now, but I'll give it another shot late.

**Comment by skoudoro** [comment]
if you look at #2013, it seems to be fixed.  I just deactivate more magic triggers from our Github settings. So I close this PR. Thanks @arokem!

**Comment by arokem** [comment]
That's great! Shouldn't we remove the appveyor config file, though?

**Comment by skoudoro** [comment]
As you said, let's keep it just in case we want to come back to Appveyor and match/reproduce our build history.

**Comment by arokem** [comment]
OK!

**Pull request closed without merging**
