### PR TITLE
CENIR 'HCP-like' multi b-value data

### PR DESCRIPTION
**Pull request by arokem**
Needed for #677

### CODE REVIEW

**Comment by MrBago** [comment]
@arokem could you use the `fetch_data` method in your fetchers? The way `fetch_data` is written, if the data exists, it confirms the md5 and return. If the md5 doesn't match or the file does not exist it will download the file. `fetch_data` has tests written for it, but we cannot write tests for each individual "fetcher."

Also, I think the "read_data" functions should call the "fetch_data" functions. If the files exist, calling the "fetcher" will simply serve to confirm the md5 is correct and the data has not been changed or corrupted. If the file does not exist, then the "fetcher" will try and download the data. Also if the reader is calling the fetcher, the fetcher can return the filenames to the reader so that we don't need to hard-code the file names in 2 different places.

This model makes for less code duplication, better testing and less hard-coding of file names, directories. Look at `fetch_standford_labels`/`read_stanford_labels` if you need an example.

**Comment by MrBago** [comment]
I think we should at some point apply this change to all the "fetchers", but for now I would settle for using it in new "fetchers".

**Comment by arokem** [comment]
Yeah - good call. I did this on #681 as well.

Once these two are merged (hint, hint), I volunteer to do a full refactor
in this direction on all of the fetchers/readers. This module is indeed a
bit of a mess right now.

**Comment by Garyfallidis** [comment]
@MrBago this looks good to me. If you agree then please go ahead and merge this.

**Comment by arokem** [comment]
Hang on with this one. As pointed out by @RafaelNH, there's currently no good way to pull the affine out from this. Working on it.

**Comment by arokem** [comment]
OK - all set with that now.

**Pull request merged**
