### PR TITLE
Add a warning on attempted import.

### PR DESCRIPTION
**Pull request by arokem**
Would this properly address #1976 ? 

The cryptic error is still raised, but is preceded by a warning: 
Screen Shot 2019-10-02 at 5 38 01 AM

### CODE REVIEW

**Comment by skoudoro** [comment]
Any chance to have a test for this PR @arokem?

**Comment by arokem** [comment]
Sorry - yes - I have this for now. But it seems to be failing... 

I don't understand why the warning is not being captured by catch_warnings. It's definitely being emitted!

**Comment by skoudoro** [comment]
Thanks! Maybe because of a [warning filter rules](https://docs.python.org/3/library/warnings.html). I do not know which one but I got this problem once.

**Comment by skoudoro** [comment]
Thank you for this @arokem! Merging

**Pull request merged**
