### PR TITLE
Adding a decorator for skipping test if openmp is not available

### PR DESCRIPTION
**Pull request by skoudoro**
The goal of this PR is to avoid test failure on mac when openmp is not avalaible. is it ok for you @matthew-brett @Garyfallidis  ?

### CODE REVIEW

**Comment by arokem** [comment]
Should address #1265

**Comment by skoudoro** [comment]
Right, I forgot it, Thanks !

**Comment by Garyfallidis** [comment]
Cool, thanks @skoudoro

**Comment by arokem** [comment]
try_branch currently in progress here: https://nipy.bic.berkeley.edu/builders/dipy-py2.7-osx-10.6/builds/714/steps/shell_9/logs/stdio

**Pull request merged**
