### PR TITLE
BF: Use np.npy_intp instead of assuming long for ArraySequence attributes

### PR DESCRIPTION
**Pull request by MarcCote**
A small patch addressing the issue @arokem raised in comment https://github.com/nipy/dipy/pull/1076#issuecomment-274866713

### CODE REVIEW

**Comment by matthew-brett** [comment]
I think you'll need to bump up the minimum Cython version from 0.18 to 0.25.1 - see requirements.txt, .travis.yml, dipy/info.py ...

**Comment by matthew-brett** [comment]
Unrelated test failure for pre-release wheels addressed by #1229.

**Comment by matthew-brett** [comment]
I get the int / long testing error reliably when using cython 0.18, 0.21, 0.24, but not 0.25.1.  All of these compile OK, the error only appears at run-time.  But why not try Cython==0.21 as the minimum dependency in `.travis.yml` and see?  I think you'll find you need Cython==0.25.1 as the minimum dependency.

**Comment by MarcCote** [comment]
@matthew-brett yes, you are right about needing Cython >= 0.25.1.

**Comment by matthew-brett** [comment]
Don't forget `dipy/info.py` and `.travis.yml` for the Cython dependency.

**Comment by MarcCote** [comment]
@matthew-brett thanks. @arokem this PR is ready.

**Comment by arokem** [comment]
LGTM. Unless someone has more comments, I can merge this tomorrow.

**Comment by matthew-brett** [comment]
Looks good to me too.

**Pull request merged**
