### PR TITLE
BF: Predict DKI with a volume of S0

### PR DESCRIPTION
**Pull request by arokem**
The first commit introduces a test that demonstrates the bug: if the `S0` input to DKI prediction is provided as a ndarray (which should be possible!), this raises an error. 

The second commit fixes this bug, by separating into two cases: one when `S0` is an ndarray (assumed to have the right shape!), and one when it is a float.

### CODE REVIEW

**Comment by arokem** [comment]
@RafaelNH : could you please take a look? Thanks!

**Comment by RafaelNH** [comment]
@arokem - excellent, well spotted! In my opinion this can be merged!

**Comment by arokem** [comment]
Does anyone have any comments here? It's just a small bugfix!

**Comment by RafaelNH** [comment]
As mention above everything looks fine here. If there isn't any objections, I will merge this tomorrow!

**Pull request merged**
