### PR TITLE
BF : Clamping of the value of v in winding function

### PR DESCRIPTION
**Pull request by GuillaumeTh**
With the float's error, it's possible to have a value of v superior at 1 (e.g 1.00000002). For resolve this, I clamp v between -1 and 1.

### CODE REVIEW

**Comment by arokem** [comment]
Any chance to get a test-case that fails without this fix?

**Comment by samuelstjean** [comment]
arccos is mathematically defined between -1 and 1 .

~~~python
In [3]: np.arccos(-1. - 1e-8)
/usr/bin/ipython:1: RuntimeWarning: invalid value encountered in arccos
  #! /usr/bin/python
Out[3]: nan

In [4]: np.arccos(1. + 1e-8)
/usr/bin/ipython:1: RuntimeWarning: invalid value encountered in arccos
  #! /usr/bin/python
Out[4]: nan

In [5]: np.arccos(1. )
Out[5]: 0.0

In [6]: np.arccos(-1. )
Out[6]: 3.1415926535897931

~~~

**Comment by GuillaumeTh** [comment]
@arokem  I can send you few trk file where we are this warning. I think we have this warning when the angle between two segments is 0.

**Comment by arokem** [comment]
@GuillaumeTh : please do share a (hopefully small :-D) trk file that has this issue.

The case you described - would that be the case when `v1 == v0`? It doesn't always cause this: 

```
In [10]: v0 = [1.0, 0.0, 0.0]

In [11]: v1= [1.0, 0.0, 0.0]

In [12]: v=np.dot(v0,v1)/(np.linalg.norm(v0)*np.linalg.norm(v1))

In [13]: tmp=np.arccos(v)

In [14]: v
Out[14]: 1.0
```

**Comment by samuelstjean** [comment]
It's a numerical issue, so if you pick 1,0,0 it<s always gonna work , there you go

~~~python
v0 = [np.sqrt(2), np.sqrt(2),np.sqrt(2)]
v1 = [-np.sqrt(2), -np.sqrt(2), -np.sqrt(2)]
v=np.dot(v0,v1)/(np.linalg.norm(v0)*np.linalg.norm(v1))

In [15]: v
Out[15]: -1.0000000000000002

In [16]: tmp=np.arccos(v)
/usr/bin/ipython:1: RuntimeWarning: invalid value encountered in arccos
  #! /usr/bin/python
~~~

**Comment by arokem** [comment]
Great. I think we've narrowed it down to a test case we can add here. Do
you want to add that as a PR against @GuillaumeTh
<https://github.com/GuillaumeTh>'s branch, @samuelstjean?

**Comment by arokem** [comment]
Thanks for the test-case! If you could make the test PEP8 compliant, that would be great (see this commit to see what that looks like: https://github.com/arokem/dipy/commit/23293d5cd7cf8c786e1d3ee66f7dba92061a669a). Other than that, ready to be merged as far as I can tell, unless someone else has objections. @samuelstjean - anything more here?

**Comment by samuelstjean** [comment]
Seems to work, or at least it does not without the fix, and it is sensible. So I approve.

**Comment by arokem** [comment]
Thanks! Merging.

**Pull request merged**
