### PR TITLE
RF: Change streamtube default thickness so that they don't look awful.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by Garyfallidis** [comment]
lol. such drama :)

**Comment by arokem** [comment]
Well, my eyes hurt :-)

**Comment by Garyfallidis** [comment]
true story :)

**Comment by Garyfallidis** [comment]
Did you check how the tutorials look with 0.1?

**Comment by Garyfallidis** [comment]
Let's move on then. We can do this later.

**Comment by arokem** [comment]
Yes. I checked a few: both with dark and light background. Both look great
with this default.

**Pull request merged**
