### PR TITLE
Change DKI_signal to dki_signal

### PR DESCRIPTION
**Pull request by RafaelNH**
To address Issue #1145

### CODE REVIEW

**Comment by RafaelNH** [comment]
@Garyfallidis - any comments?

**Comment by arokem** [comment]
Do we need to do something for back-compatibility and deprecation

**Comment by Garyfallidis** [comment]
Question. No tutorial or other test is using this function?

**Comment by arokem** [comment]
Not as far as I can tell (`git grep DKI_signal`)

**Comment by Garyfallidis** [comment]
Okay thanks. This is a minor change so I am going to merge...

**Pull request merged**
