### PR TITLE
Added Travis-CI badge

### PR DESCRIPTION
**Pull request by waseem18**

### CODE REVIEW

**Comment by samuelstjean** [comment]
https://github.com/nipy/dipy/pull/617

Of course if you have new arguments I'm all for it.

**Comment by waseem18** [comment]
Okay! What about Gitter badge?

**Comment by Garyfallidis** [comment]
Hi @waseem18 and thank you very much for your PR but there is already a PR about the gitter button. Now, we decided some time ago to not add the travis badge in the readme because sometimes travis is failing not because the tests are failing but because of technical issues with travis itself. Some developers from other projects expressed their frustration to us with this badge. But I see that Travis is constantly improving so we can discuss this again later. Finally, If you are interested in participating to GSoC please send me your CV by e-mail.

**Comment by waseem18** [comment]
Sure @Garyfallidis  :+1:

**Pull request closed without merging**
