### PR TITLE
DOC: Added a coverage badge to README.rst

### LINKED ISSUE #1071: report coverage and add a badge?
Hi guys.  I see that you are running tests for coverage and even submitting to coveralls... but for some reason coveralls wasn't activated for nipy/dipy... since I didn't find any issue here in the tracker about coveralls being evil, I have enabled it.  Myself recently I have preferred codecov service. With their extension for the browsers to see pull requests annotated line by line regarding coverage -- just awesome

### PR DESCRIPTION
**Pull request by yarikoptic**
Closes #1071

### CODE REVIEW

**Comment by yarikoptic** [comment]
woohoo -- coverage is now reported... let me add also codecov -- once again, like that one better ;)

**Comment by arokem** [comment]
In the past, we've refrained from adding these badges (https://github.com/nipy/dipy/pull/860). I don't mind adding this badge. Do I understand correctly that it's unaffected if Travis flakes out for some reason? That was the main objection to adding the badges before.

**Comment by yarikoptic** [comment]
not sure about travis flaking out effect... does it happen often that travis fails running tests on master?

**Comment by yarikoptic** [comment]
and now get codecov badge just in case ;)

**Comment by yarikoptic** [comment]
if still in doubt you can preview badges on https://github.com/yarikoptic/dipy/blob/b3be38e5ac73a841fa113ee51f55e29de9ee6703/README.rst
(coveralls is not reported since it requires it being merged first)

**Comment by arokem** [comment]
I am +1 for adding these badges. Anyone else have any opinion?

**Comment by yarikoptic** [comment]
It makes two of us... the others are silent so I will use my superpowers!

**Pull request merged**
