### PR TITLE
WIP: affine map tests

### PR DESCRIPTION
**Pull request by matthew-brett**
Here I did the change to `set_affine` I mentioned in the PR discussion
https://github.com/nipy/dipy/pull/690#discussion_r36034792

I was going to add a test, but then I noticed that ``AffineMap`` has no tests -
can that be right?

### CODE REVIEW

**Comment by Garyfallidis** [comment]
Probably, because the AffineMap was to be discussed in a following PR and first see if it can be used with SLR.

**Comment by matthew-brett** [comment]
So was the plan to leave AffineMap in without tests until then?    Can you be say more about what this future PR might be?

**Comment by Garyfallidis** [comment]
Hi @matthew-brett ! Thanks for the reminder. No, this is definitely not staying in without tests. The first question should be if we need the AffineMap. The AffineMap is currently not being used for registration. The tutorial is misleading!

The PR should be about the AffineMap and it's possibility to be used with SLR. Maybe two PRs in total. One from me and one from Omar. Mine will probably come later. There was also some discussion about separating the linear metrics with the nonlinear. I would like to see a PR for that too.

On a side note I am currently running both the affine registration and the nonlinear registration with some demanding data. All good so far.

**Comment by matthew-brett** [comment]
It looks like the `AffineMap` is being used in `MutualInformationMetric`.  Not so?

**Comment by Garyfallidis** [comment]
I was talking about this tutorial https://github.com/nipy/dipy/blob/master/doc/examples/affine_registration_3d.py#L50
The AffineMap is used there but not really used for registration.

**Comment by Garyfallidis** [comment]
Oh damn. I missed this. He has used it in the actual imaffine file. No okay I understand now why you were worried about this. @omarocegueda can you make a PR asap with tests for the AffineMap?

**Comment by omarocegueda** [comment]
Hi @matthew-brett @Garyfallidis,
>can you make a PR asap with tests for the AffineMap

sure!, this will be my priority today.

**Comment by omarocegueda** [comment]
Hi @matthew-brett , @Garyfallidis,
I just added the missing tests for AffineMap in PR #700 (I included this PR's commit there too). This is the reported test coverage (97%):
https://travis-ci.org/nipy/dipy/jobs/75506207
Thanks!

**Comment by arokem** [comment]
Is this superseded by #700? Should we close this one?

**Comment by omarocegueda** [comment]
>Is this superseded by #700? Should we close this one?

Yes, #700 includes Matthew's change.

**Pull request closed without merging**
