### PR TITLE
[Fix] Cython syntax error

### PR DESCRIPTION
**Pull request by skoudoro**
This PR should fix the "PRE" Travis build error as you can see [here](https://travis-ci.org/nipy/dipy/jobs/487740657#L1346)

### CODE REVIEW

**Comment by arokem** [comment]
Looks good, of course. Do you understand why we missed this until now?

**Comment by arokem** [comment]
Gotcha. That makes sense! Thanks for fixing this!

**Comment by arokem** [comment]
I'll wait for Travis to finish, just in case anything comes up and then merge, since this is fairly uncontroversial. We're going to run into more and more of this kind of stuff, now that the community is moving away from Python 2. We should probably make a plan to transition away from Python 2 support too. I'll open an issue to discuss.

**Comment by skoudoro** [comment]
It seems that this PR fix the syntax error, but a lot of new Cython errors appears on PRE. Theses errors deserve theirs owns PR's, I think.

**Comment by arokem** [comment]
Hi Serge - sorry for the slow reply. Do you want me to merge this, or wait for the fix on PRE? I am happy either way.

**Comment by skoudoro** [comment]
No worries Ariel, I am not in a hurry. Yes, you can go ahead to merge this, I will create a new PR to understand why the new Cython version does not find all *.pxd files

**Pull request merged**
