### PR TITLE
improvements for denoise/denspeed.pyx

### PR DESCRIPTION
**Pull request by sdorkenw**
Speedup for multithreaded implementation
New implementation of nlmeans that outperforms the current implementation especially when no mask is given by removing redundant computations. Currently only as single threaded version -> use this for num_threads == 1 and fall back to old implementation elsewise

### CODE REVIEW

**Comment by Garyfallidis** [comment]
Hi @sdorkenw thank you for this PR. What is the actual speedup achieved here? Does the code duplication worth the effort if this works only for 1 thread? Also there are no tests.

**Comment by sdorkenw** [comment]
Hi @Garyfallidis. I plotted the actual speed in dependency of the number of voxels that are masked (= denoised). I also wrote a multiprocessed version of the "new" implementation, but it was not always faster than the original one. I am happy to also share/include that code.

data size: 145, 174, 145
the mask was produced with median_otsu and dpg.gradient_table and then dilated / eroded

speedup
time_comp_conv

**Comment by arokem** [comment]
It looks like a lot of the benefit is probably coming from the first commit here, and not necessarily from the reimplementation of the internals convolution  

Maybe we can just take that (it's a one-line change, that changes the scheduling of `prange`)?

**Comment by arokem** [comment]
Hey @sdorkenw - could we have a separate PR just for that first commit? Seems like that would already give us a substantial speed up!

**Comment by arokem** [comment]
Looks like this was superseded by #1065. Closing.

**Pull request closed without merging**
