### PR TITLE
Added to quantize_evecs: multiprocessing and v

### PR DESCRIPTION
**Pull request by xjhc**
Added a multiprocessing option and the ability to choose which eigenvector to use as primary vector for fiber tracking.

### CODE REVIEW

**Comment by arokem** [comment]
Interesting. Do you have any idea whether this actually improves performance in practice?

**Comment by xjhc** [comment]
Paralleling over N cores gives roughly a N-fold speedup for a test dataset of size 1.5 GB. Because the original implementation also reshapes the array (for vectorization), there is very little additional overhead.

This allows processing of 210 GB array of eigenvectors (i.e. 70 GB array of the primary eigenvector) within ~2 hours on Intel Xeon E5-2667 v2 with 20 x SSD on RAID 10.

Also, the ability to choose the primary eigenvector is useful for studies like doi: 10.1016/j.neuroimage.2015.01.061, doi:10.1016/j.cell.2016.05.010 and doi: 10.1117/1.JBO.20.3.036003, where the eigenvector associated with the smallest eigenvalue is actually the primary eigenvector for tracking.

**Comment by arokem** [comment]
OK - sounds like there is a clear use case for this. I do have a couple of comments about the code. The first is that we should add some tests for this functionality. The other is a suggestion: instead of having two different variables for `nbr_processes` and `parallel`, would it make sense to have just one variable `nbr_processes`? Set it to 1 per default, which means no parallelism, -1 means as many processes as possible (the return value of `cpu_count`), etc. Does that make sense, or am I missing something?

**Comment by arokem** [comment]
@xjhc : any more thoughts here? Have you had a chance to write tests for this functionality?

**Comment by xjhc** [comment]
Thanks for the mention - I hadn't checked in on Github lately. 

And thanks for the insightful suggestions. 
- I'll add the tests (in accordance with other tests in this project); I really should've done this before.
- I'll make the update for the nbr_processes.

**Comment by xjhc** [comment]
Just an update - I finished the tasks, but haven't had the opportunity to test it out yet. I'll have access to our workstation in two days, and I hope to get it done then. Thanks for your patience!

**Comment by arokem** [comment]
OK - great. Let us know when you have a chance to try this out, and to push the changes here for review.

**Comment by xjhc** [comment]
Everything's good to go.

**Comment by arokem** [comment]
Sorry for the long gap here. Could you please run a PEP8 checker on the tests? There are a lot of missing white-space in that file. We've generally been following a convention where tests of a module are all in one file, in this case in `test_dti`. Would you mind moving the tests into that file? Thanks again.

**Comment by arokem** [comment]
Pinging @xjhc : Have you had a chance to run a PEP8 checker on this? Thanks!

**Comment by arokem** [comment]
This is superseded by #1164

**Pull request closed without merging**
