### PR TITLE
Return numpy arrays instead of memory views from cython functions

### PR DESCRIPTION
**Pull request by omarocegueda**
Workaround to prevent this kind of memory leaks:
https://github.com/omarocegueda/cython_leak_repro/blob/master/memory_leak.ipynb
which occur when using memory views allocated and returned from cython functions

### CODE REVIEW

**Comment by arokem** [comment]
I've pushed a branch with this change and the appveyor config here: 

https://github.com/arokem/dipy/tree/omarocegueda-wrap_memviews-appveyor

It's running an appveyor build over here: 
https://ci.appveyor.com/project/arokem/dipy/build/1.0.576

**Comment by omarocegueda** [comment]
Awesome! let's see what it says =)

**Comment by arokem** [comment]
Still no joy:
https://ci.appveyor.com/project/arokem/dipy/build/1.0.576/job/4j8cy33yvdesmd66

**Comment by Garyfallidis** [comment]
Rather than using np.array(memview) it would be interesting to check if it is more advantageous to use np.asarray see here
http://stackoverflow.com/questions/20978377/cython-convert-memory-view-to-numpy-array

**Comment by Garyfallidis** [comment]
@omarocegueda can you update this PR? It will be nice to get rid of the memory leaks (or any copies) in this release.

**Comment by omarocegueda** [comment]
No problem!, now using np.asarray(...). This will eliminate the memory leaks, but not yet the issue on appveyor.

**Comment by arokem** [comment]
That's OK. We'll figure out the appveyor thing on another branch. For the time being, @Garyfallidis - is this ready to be merged?

**Comment by Garyfallidis** [comment]
Yes!

**Comment by omarocegueda** [comment]
Thank you guys! =)

**Pull request merged**
