### PR TITLE
Deprecate Reconst*Flow

### PR DESCRIPTION
**Pull request by skoudoro**
This PR start a new deprecation cycle for `dipy.workflows.reconst`. All class `Reconst*Flow` has been renamed `Fit*Flow`.

### CODE REVIEW

**Comment by Garyfallidis** [comment]
I am not sure about this change. I prefer if the workflow api is more consistent with the internal api rather than the cmd names.

**Comment by Garyfallidis** [comment]
Let me think ...

**Comment by Garyfallidis** [comment]
a bit more about this... :)

**Comment by skoudoro** [comment]
Any opinion about this @Garyfallidis? @arokem? Other?

**Comment by arokem** [comment]
Sorry I missed this. LGTM!

**Pull request closed without merging**
