### PR TITLE
DOC: Use triple double-quoted strings for docstrings.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix
```
Triple double-quoted strings should be used for docstrings.
```

PEP8 warning.

Indeed, according to
https://www.python.org/dev/peps/pep-0008/

*For triple-quoted strings, always use double quote characters to be
consistent with the docstring convention in PEP 257.*

### CODE REVIEW

**Comment by arokem** [comment]
Thanks for doing this @jhlegarreta! As you can see, this triggered a more thorough PEP8 checking on every file you touched. Do you want to go ahead and fix these issues as well, while we're here? If you don't, I can also just merge this one as soon as the CI finishes. It all looks good to me.

**Comment by jhlegarreta** [comment]
Let's see how 0487ec2 behaves.

**Comment by jhlegarreta** [comment]
The reported test failure is related to #1698.

**Comment by skoudoro** [comment]
Thank you @jhlegarreta, merging

**Pull request merged**
