### PR TITLE
Use integer division in reconst_gqi.py

### PR DESCRIPTION
**Pull request by ghoshbishakh**

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
lets check all the examples before merging this one

**Comment by arokem** [comment]
Just checking: have you had a chance to check the other examples? I propose that add the changes to the other examples on this same PR.

**Comment by ghoshbishakh** [comment]
@arokem no still a few a left.

**Comment by ghoshbishakh** [comment]
@arokem All examples are working now! Ready to merge.

**Comment by arokem** [comment]
Awesome. Thanks for doing this!

**Pull request merged**
