### PR TITLE
TST: Test for invariance of model_params to splitting of the data.

### PR DESCRIPTION
**Pull request by arokem**
This looks like a bug to me: it shouldn't matter whether you fit the
entire data array or just one.

This happens because min_signal currently depends on the entire data array
that is passed, and that varies here depending on whether only one voxel
or the entire array is passed.

For now, I only have the bug and no fix, hence the WIP. Suggestions most welcome!

### CODE REVIEW

**Comment by arokem** [comment]
How about this for a solution? Removing the WIP tag.

**Comment by arokem** [comment]
Anyone want to give this one a review? It's a rather simple bug that really shouldn't be here, with a rather simple fix (I think) -- less than 40 lines of changes.

**Comment by MarcCote** [comment]
LGTM. It makes sense to use a constant value for the min signal value if none was provided.

**Comment by MarcCote** [comment]
Oh, there is now a conflict because I merged your other PR.

**Comment by arokem** [comment]
Rebased! 

It looks like all conflicts were in docstrings, but maybe let Travis run through this, just to be on the safe side.

**Pull request merged**
