### PR TITLE
DOC - updated streamline_tools example with the LocalTracking Framework

### PR DESCRIPTION
**Pull request by gabknight**
Changed the call from EuDX to LocalTracking. EuDX is still the algorithm use here, but in the new framework.

### CODE REVIEW

**Comment by skoudoro** [comment]
Thanks @gabknight. Should we keep the `Eudx` class or more generally `eudx.py` (old framework)?

**Comment by gabknight** [comment]
@skoudoro, no, no need to keep it as it is essentially the same as LocalTracking with `PeaksAndMetricDG`. I want to refactor this: remove eudx.py, rename `PeaksAndMetricDG` to EudxDG, and move the eudx tests.

This will be in the another PR addressing #1501.

**Comment by skoudoro** [comment]
ok, sounds good! Do you need help? Today, I can do this part of removing `eudx.py` and `renaming PeaksAndMetricsDG`

**Comment by gabknight** [comment]
@skoudoro sure give it a go if you have time. The tricky part will adjust the tests. It will be very good to do it, as the current `PeakAndMetricDG` is not properly tested.
If you don't, I will do it at the time RF the tracking.local package. I'll be away from now until 19.07, I'm not sure I can make it for the next release.

**Comment by skoudoro** [comment]
I just run the documentation and this example, everything looks good. merging

Thanks @gabknight!

**Pull request merged**
