### PR TITLE
DOC: switch to using mathjax for maths

### PR DESCRIPTION
**Pull request by matthew-brett**
Mathjax is much quicker.

### CODE REVIEW

**Comment by arokem** [comment]
+1 from me on this. Any objections?

**Comment by Garyfallidis** [comment]
Yes, please merge only if you test it first. I mean render the website and look at the actual math in the examples. Maybe it needs some dependencies or it has other issues.

**Comment by Garyfallidis** [comment]
The time that takes pngmath to render is not an issue. Most of the time is spent on running the examples.

**Comment by matthew-brett** [comment]
The mathematics will look nicer and scale to browser zooming level with mathjax.

**Pull request merged**
