### PR TITLE
DOC: Add the DKI reconstruction example to the list of valid examples.

### PR DESCRIPTION
**Pull request by arokem**
This is a (very) small change in the documentation, but also a more general question about how we should go about updating the documentation, while keeping it compatible with the 0.10.1 released version. Is the right thing to make the PRs on the documentation against the maint/0.10.x branch and then merge (cherry pick?) from there into master?

### CODE REVIEW

**Comment by Garyfallidis** [comment]
I don't know what is the best way to do this. I think we need to experiment a bit.

**Comment by Garyfallidis** [comment]
In the meantime I think because already other important PRs for 0.10.x have been merged in the master we should add that one too. Agreed?

**Comment by arokem** [comment]
Sure. We can also have the discussion on some other channel. Any reason not to merge this?

**Comment by arokem** [comment]
ping!

**Pull request merged**
