### PR TITLE
get_data consistence

### PR DESCRIPTION
**Pull request by skoudoro**
The goal of this PR is to resolve an old issue #10 .

Can you have a look @matthew-brett @arokem ?

### CODE REVIEW

**Comment by arokem** [comment]
This looks good to me.

 @matthew-brett made the comment that it would be preferable to return data, but I think that returning file-names makes sense. It's more transparent for users to see how they would adapt this to their own data, when the file-names are explicitly mentioned. 

But maybe @matthew-brett has reconsidered this since 2011? 😄

**Comment by matthew-brett** [comment]
This looks better to me - thanks.  I think it's fine to return files, just as long as it's obvious from the docstrings / variable names that that is the case.  For example, how about `get_data_fnames` rather than `get_data` ?  Would that help with backwards compatibility?

**Comment by skoudoro** [comment]
Explicit better than implicit (like you said @arokem ) so I agree with @matthew-brett. I prefer `get_data_fnames`than `get_data`. I made this mistake the first time because I was not expecting filenames.

@Garyfallidis, any thoughts ? 

If it is ok for all of you, I can do a new PR with this change.

**Comment by arokem** [comment]
You can make that change on this PR in a follow-up commit

**Comment by Garyfallidis** [comment]
``get_fnames`` or ``get_data_fnames`` is fine for me. When refactoring this function take your time it is used in many many places.

**Comment by arokem** [comment]
Thinking about this a bit more, I prefer `get_fnames`. It's already in the
`dipy.data` namespace.

**Comment by skoudoro** [comment]
Any thought concerning this PR?

**Comment by skoudoro** [comment]
Thanks!

**Pull request merged**
