### PR TITLE
RF - EuDX legacy code/test

### PR DESCRIPTION
**Pull request by gabknight**
WIP waiting on: #1887, #1881 

This addresses in part #1501 

- removed legacy EuDX code and tests
- renamed `PeaksAndMetricDirectionGetter` to `EuDXDirectionGetter`

@arokem `dipy/tracking/tests/test_life.py` uses EuDX to generate streamlines, and then compare the LiFE results with the results of the Matlab implementation. `LocalTracking` does not produce precisely the same streamlines as EuDX (e.g. the last points of the streamlines are not kept anymore), making the test fail. To solve this, I propose we save the former EuDX streamlines and load the trk in this test. What do you think?

### CODE REVIEW

**Comment by gabknight** [comment]
@arokem I went ahead and added the tracking file from the legacy EuDX code to dipy/data. This way the LiFE matlab_results and the streamlines will always match. Is that sounds OK?

**Comment by skoudoro** [comment]
Hi @gabknight, Thank for this PR. I did almost the same on a local branch and I forgot to push and create a PR. My bad for duplicating the work and sorry for that. Otherwise, it looks good, I just need to tests your branch. Thank you again!

**Comment by gabknight** [comment]
thx @skoudoro. No worries, please let me know if you did differently. I want to also move tracking/local to just tracking, and remove local in names, as discussed in the dipy meeting a few months ago. Did you do some work there? Otherwise, I will be finishing this PR in the coming days.

**Comment by skoudoro** [comment]
> Did you do some work there?

Not yet, because I would like to see #1912 and #1896 merged before

**Comment by gabknight** [comment]
OK. Let's wait for merging #1912, #1896. I suggest we make a new PR for the RF of `localtracking`, and merge this one separately.

**Comment by Garyfallidis** [comment]
Hi @gabknight, I fixed a conflict in test_propagation as  #1912 and #1896 are now merged.
Will merge this PR today if the CIs are green.

**Comment by skoudoro** [comment]
Thank you @gabknight, merging

**Pull request merged**
