### PR TITLE
Faster dti odf

### PR DESCRIPTION
**Pull request by arokem**
Speeds up DTI odf calculation, by calculating it only over regions of the volume that have non-zero eigen-values.

### CODE REVIEW

**Comment by arokem** [comment]
This saves a little bit of time for the case in scratch/profile_dti.py: 

this branch: 48.5043 s
master: 57.4576 s

But should save substantially more time when a mask is used.

**Comment by arokem** [comment]
This one is also an easy review: <40 lines of changed code for a 12% speedup for something that some users probably do 20 times a day. Any one want to take a look?

**Comment by MarcCote** [comment]
LGTM. It avoids divisions by zero and simplifies the code.

**Comment by arokem** [comment]
Thanks for taking a look. Now also rebased for ease of merging.

**Comment by MarcCote** [comment]
@arokem : it seems the rebase went wrong?

**Comment by arokem** [comment]
Looks like Travis was having a hard time connecting to Github. I just repushed that last commit.

**Comment by MarcCote** [comment]
@arokem: Should I wait for you to add a small test that actually uses the mask (see codecov)?

**Comment by arokem** [comment]
oh yeah - thats no good. please wait. ill get to it in the weekend, i hope

On Oct 26, 2016 2:19 PM, "Marc-Alexandre Côté" <notifications@github.com>
wrote:

@arokem <https://github.com/arokem>: Should I wait for you to add a small
test that actually uses the mask (see codecov)?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nipy/dipy/pull/1064#issuecomment-256433883>, or mute
the thread

**Comment by arokem** [comment]
How about this? On my machine, the `dti` module is currently at 99% coverage.

**Comment by MarcCote** [comment]
Excellent!

**Pull request merged**
