### PR TITLE
MAINT: work around scipy bug in sph_harm

### PR DESCRIPTION
**Pull request by argriffing**
related bugs/issues/PRs:
https://github.com/scipy/scipy/issues/4887
https://github.com/scipy/scipy/issues/4895
https://github.com/nipy/dipy/issues/611
https://github.com/nipy/dipy/pull/612

### CODE REVIEW

**Comment by argriffing** [comment]
I don't think the dipy travis config uses a new enough scipy to test this change.

**Comment by arokem** [comment]
I think you are correct. Let me try this out on my laptop.

**Comment by arokem** [comment]
I can confirm that this works on scipy 0.15 on my laptop, killing #611 and obviating #612.

**Comment by arokem** [comment]
Another option is to wait until this is fixed upstream in scipy, and keep using our implementation until that time (which is what #612 now implements). Any thoughts from anyone else?

**Comment by arokem** [comment]
Also: thanks so much for taking a look!

**Comment by pv** [comment]
This is probably a numpy bug in ufunc dtype selection (which is choosing float32 instead of float64), so the upstream scipy fix will also be a workaround (and you will have to wait for it for a moderately long time as your users would need to use a new enough Scipy version). The problem is fairly restricted --- it occurs only in the special case when all arguments are integers, at least one of the first two are arrays, *and* both of the angle arguments are integer scalars.

**Comment by arokem** [comment]
Thanks for clarifying. I still think that we can wait. We do have a fully
functioning solution in our code. This particular PR seems to solve the
problem for only a small subset of the potential failure modes of this
function (only when used through `sh_to_rh`). I prefer the solution we have
on #612, and waiting.

Anyone else but me have any opinions on this?

**Comment by argriffing** [comment]
> This particular PR seems to solve the problem for only a small subset of the potential failure modes of this function (only when used through `sh_to_rh`)

Sorry this PR was a bit tongue-in-cheek.  If you never want low-precision output from `sph_harm` then I think you could change
`return sph_harm(m, n, theta, phi)`
to
`return sph_harm(m, n, theta, phi, dtype=complex)`
at
https://github.com/nipy/dipy/blob/maint/0.9.x/dipy/reconst/shm.py#L189

**Comment by arokem** [comment]
Oh - you shouldn't mess with me that way. I'm way too slow to get that kind
of humor. And awfully gullible, when it comes to PRs.

Thanks for the new suggestion. This one was serious, right?

Now implemented in #612.

**Comment by argriffing** [comment]
@pv Do you have a suggestion for the best practice for working around this bug in packages downstream from numpy/scipy?  I think the method in this PR would work for `dipy`, and that the less ad-hoc workaround of adding `dtype=complex` in the `dipy` wrapper of `sph_harm` would also work (assuming that they never want `complex64` output under any circumstance).  Do you agree that the second of these two choices would be more appropriate?  Is there an even better workaround?

**Comment by Garyfallidis** [comment]
Ping! How is this PR going on? Still a work in progress?

**Comment by arokem** [comment]
Hi! This one is probably superseded by #612. Closing this one for now.

**Pull request closed without merging**
