### PR TITLE
Fix: numpy legacy print again...

### PR DESCRIPTION
**Pull request by skoudoro**
set version of Numpy print options due to recent change

### CODE REVIEW

**Comment by skoudoro** [comment]
It seems to be good now @Garyfallidis :-)

**Comment by fissell** [comment]
Hi, 
 np.set_printoptions(sign='legacy') breaks my dipy test.  
On an Ubuntu machine I have numpy '1.14.0' and installed dipy
via easy_install --upgrade dipy to get dipy version '0.13.0'.
dipy.test() generates 2 errors because 
File "/data//lib/python2.7/site-packages/dipy-0.13.0-py2.7-linux-x86_64.egg/dipy/testing/__init__.py",
			   line 38, in setup_test   np.set_printoptions(sign='legacy')
indicates:  site-packages/numpy-1.14.0-py2.7-linux-x86_64.egg/numpy/core/arrayprint.py", line 83, in _make_options_dict
    raise ValueError("sign option must be one of ' ', '+', or '-'")

Is there a version of dipy greater than 0.13.0 where this is fixed ?

thanks
Kate

**Comment by skoudoro** [comment]
Hi @fissell,

> Is there a version of dipy greater than 0.13.0 where this is fixed?

Not yet.

Dipy 0.14.0 will be released during the first week of February. This release includes this PR. 
So at the moment, you have the following options:
- wait 20 days for the release.
- use the dev-master branch.
- downgrade Numpy to 1.13 or Dipy to 1.12

**Comment by matthew-brett** [comment]
Hi Kate,

We may well have left this in the instructions somewhere, but `easy_install` is severely outdated now - and will likely cause ugly problems later - for example when upgrading - see https://matthew-brett.github.io/pydagogue/installing_on_debian.html for some recommendations.

Cheers,

Matthew

**Comment by fissell** [comment]
Thanks Matthew and Serge !

**Pull request merged**
