### PR TITLE
Tissue Classifier tracking example - changed seeding mask to wm only voxels

### PR DESCRIPTION
**Pull request by gabknight**
Following discussion in issue #831, this PR changes the seeding mask to voxel with 100% wm partial volume fraction. Seeds placed in voxel with a partial volume fraction of gm > 0.5 created unwanted short streamlines.

Thanks @samuelstjean, @arokem

### CODE REVIEW

**Comment by arokem** [comment]
Thanks @gabknight - for the quick turnaround! @samuelstjean - please confirm that this resolves the issue you reported. And thanks for noticing that!

**Comment by samuelstjean** [comment]
There is some other weird thing I wanted to look at, and completely forgot what it was. Will come back to me in a few days hopefully.

**Comment by arokem** [comment]
In the meanwhile, could you please confirm that this does resolve your previous complaint?

**Comment by samuelstjean** [comment]
Seems good regarding the small fibers, lots of green fibers are gone though. 

screenshot from 2016-02-03 14 33 25

All fibers
screenshot from 2016-02-03 14 36 20


As gab suggested in an internal discussion, adding a length threshold to the tracking api would also help, someday. So it does fix the immediate problem, but as some stuff is gone, anyone who knows anatomy wants to pitch in?

**Comment by gabknight** [comment]
The partial volume fraction maps are not perfect (e.g. there is false gm between the ventricles and the CC), which explains the stopped green streamlines on the first figure. 

Streamlines can easily be filtered by their length a posteriori. It won't be hard to included this filtering in the tracking as well..

**Comment by Garyfallidis** [comment]
This looks ready to me. Anyone against merging it?

**Comment by Garyfallidis** [comment]
Nobody replied so I am assuming this is okay. Thx Gab and Sam reporting it. Any improvements in another PR please.

**Pull request merged**
