### PR TITLE
Plot both IVIM fits on the same axis

### PR DESCRIPTION
**Pull request by arokem**
This is a small follow-up to #1789, in which the varpro and lm are plotted together. 

@ShreyasFadnavis : could you please take a look?

### CODE REVIEW

**Comment by ShreyasFadnavis** [comment]
Thanks a lot @arokem !! LGTM :+1: @Garyfallidis @skoudoro can you merge?

**Comment by skoudoro** [comment]
I still have the issue below (overlap) can you rebase your branch to have the last change @arokem?

measured_S0

**Comment by arokem** [comment]
That's odd. That branch is up to date with master.

**Comment by skoudoro** [comment]
Wow, ok, sorry for that. Can you update this plot too? Otherwise, this PR looks good to me too, I can merge it

**Comment by arokem** [comment]
Update which plot? It looks like this when I run that example: 

ivim_voxel_plot

**Comment by skoudoro** [comment]
I agree this one is perfect, and this is the purpose of this PR. But I wonder whether you could fix the other one too (measure_S0.png on my previous comment) or if we should do it on a new PR.

**Comment by arokem** [comment]
Oh -  that's silly. I thought you were referring to the line plot. This one
is, indeed, broken.

Fixing!

**Comment by arokem** [comment]
OK. Should be fixed now!

**Comment by skoudoro** [comment]
Yes, I just tested it, thank you! merging

**Pull request merged**
