### PR TITLE
WIP: try out Stefan Behnel's cython coverage

### PR DESCRIPTION
**Pull request by matthew-brett**
Trying Stefan's coverage work for Cython; see:

http://blog.behnel.de/posts/coverage-analysis-for-cython-modules.html

### CODE REVIEW

**Comment by arokem** [comment]
Happy days!

It looks like you'll need to update the wheelhouse for us to see the
results of this on travis, right?

**Comment by stefanv** [comment]
I think you'll have to change the Travis script to install Coverage directly from the bitbucket repository at https://bitbucket.org/ned/coveragepy

**Comment by stefanv** [comment]
Actually, that's not true; I see an alpha is out: https://pypi.python.org/pypi/coverage/4.0a5

**Comment by stefanv** [comment]
https://github.com/matthew-brett/dipy/pull/2

**Comment by matthew-brett** [comment]
The coverage needs absolute latest Cython master and Coverage master - I think the alpha release of coverage will not work.  There are still some problems even so:

https://groups.google.com/forum/#!topic/cython-users/EgWSRVuNHlA

**Comment by Garyfallidis** [comment]
Any progress here? Should we revisit later?

**Comment by Garyfallidis** [comment]
No progress on this PR. Any ideas? Is it now easier to measure Cython coverage?

**Comment by stefanv** [comment]
According to http://docs.cython.org/en/latest/src/tutorial/profiling_tutorial.html, coverage causes significant slowdown for Cython, so you'll have to add a separate matrix entry.

**Comment by arokem** [comment]
Looks like this is not going anywhere. I'll close for now.

**Pull request closed without merging**
