### PR TITLE
DOC: Remove Sourceforge related makefile things. Add the gh-pages upl…

### PR DESCRIPTION
**Pull request by arokem**
…oader.

### CODE REVIEW

**Comment by Garyfallidis** [comment]
Yo. Although there is now the shell script doc/upload-gh-pages.sh this is not being called by the Makefile. Also you need to update the documentation here http://nipy.org/dipy/devel/make_release.html#other-stuff-that-needs-doing-for-the-release if you haven't already. 

I would recommend also writing a bit of text on what this does in the Makefile.  Sounds good?

**Comment by arokem** [comment]
How's this?

**Comment by matthew-brett** [comment]
Looks OK to me.

**Comment by matthew-brett** [comment]
Any more comments here?   I'll merge soon otherwise.

**Comment by arokem** [comment]
Ping!

**Pull request merged**
