### PR TITLE
FIX: Use absolute imports in io

### PR DESCRIPTION
**Pull request by souravsingh**
Changes relative imports to absolute imports.
Fixes https://github.com/nipy/dipy/issues/997

### CODE REVIEW

**Comment by theaverageguy** [comment]
I think it should be " from dipy.io import * " @souravsingh . The build is failing.

**Comment by theaverageguy** [comment]
Please do correct me if I am wrong though. :)

**Comment by arokem** [comment]
You might want to run the tests locally on your machine before pushing. That way, you don't have to wait for the Travis bot to report on the errors :-)

**Comment by sahmed95** [comment]
the relative import is ... three directories up from dipy
```python
from dipy import io
```

**Comment by arokem** [comment]
Yeah, I think @sahmed95 is correct.

**Comment by theaverageguy** [comment]
Will fix in a while.

**Comment by souravsingh** [comment]
I have made the changes in ``test_io.py``

**Comment by arokem** [comment]
Did you run the tests on your machine? Did they pass?

**Comment by souravsingh** [comment]
I ran the tests and all of them passed

**Comment by arokem** [comment]
:+1: Great! This now all looks fine to me. I'll wait for feedback from others, and merge in a few days if I don't hear anything.

**Pull request merged**
