### PR TITLE
DOC: Fix missing reference to QuickBundles paper.

### LINKED ISSUE #1371: Quickbundles tutorials miss reference
Some of the segmentation tutorials using QuickBundles do not have a reference to the original QuickBundles paper.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix missing reference to QuickBbundles paper in the "Enhancing
QuickBundles with different metrics and features" example:
http://nipy.org/dipy/examples_built/segment_extending_clustering_framework.html#example-segment-extending-clustering-framework

Fixes #1371.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@skoudoro @Garyfallidis Please review this PR. Thanks.

I did a search for `QuickBundles` in the `doc\examples` folder and only the following files contain the string:
```
segment_clustering_features.py
segment_clustering_metrics.py
segment_extending_clustering_framework.py 
segment_quickbundles.py
``` 
So I think the PR closes the referenced issue.

If you happen to know another example that uses QuickBundle behind the scenes, please let me know to incorporate it to this PR.

**Comment by jhlegarreta** [comment]
Build failures are
- Related to #1435
- `TypeError: type numpy.ndarray doesn't define __round__ method` in `dipy.reconst.tests.test_dti.test_mask`

**Comment by arokem** [comment]
Is the latter somehow related to #1399/ #1400 0?

**Comment by jhlegarreta** [comment]
@arokem Certainly it looks like it is. However, #1400 was merged, and hence I do not see why the error should persist.

**Comment by skoudoro** [comment]
Hi @jhlegarreta, can you rebase all your PR? we just fixed the Cython problem and most of your PR seems ready to be merged. Thanks !

**Comment by jhlegarreta** [comment]
@skoudoro 97a7f2e was rebased on master. Thanks for working on the Cython issues !

**Comment by skoudoro** [comment]
LGTM, I do not see any other occurrence too. Thanks @jhlegarreta! merging !

**Pull request merged**
