### PR TITLE
Fix 1119

### PR DESCRIPTION
**Pull request by arokem**
Address #1119

### CODE REVIEW

**Comment by arokem** [comment]
I've started a try_branch job on one of the failing bots, to make sure this helps: 

http://nipy.bic.berkeley.edu/builders/dipy-bdist-whl-2.7/builds/44

**Comment by matthieudumont** [comment]
Tested it, works flawlessly.

For the XXX comments: 

-get_sub_runs does not needed to be overloaded in combined_workflow but thats it. If someone creates a new workflow or combined workflow, he does not need to overload it. 

-From what I can see, workflow.set_sub_flows_optionals has no business there. The real implementation is in combined_workflow. Probably made sense at one point in the dev and I forgot to remove it. I think it can be removed (along with the test dipy.workflows.tests.test_workflow.test_set_sub_flows_optionals).

**Comment by arokem** [comment]
On Fri, Sep 16, 2016 at 10:11 AM, matthieudumont <notifications@github.com>
wrote:

> Tested it, works flawlessly.
>
> For the XXX comments:
>
> -get_sub_runs does not needed to be overloaded in combined_workflow but
> thats it. If someone creates a new workflow or combined workflow, he does
> not need to overload it.
>
> Thanks for clarifications. I am still not sure I understand. Why do we
need a class method that returns an empty list?

**Comment by arokem** [comment]
This is failing coveralls because of the removal of the (unnecessary) test removed in the last commit.

**Comment by arokem** [comment]
Is this GTG?

**Comment by matthieudumont** [comment]
Yes GTG, do I need to merge it?

**Comment by arokem** [comment]
If you have push rights here, please do. Otherwise, one of the core maintainers should come along and press that green button.

**Pull request merged**
