### PR TITLE
FIX: Stateful tractogram examples

### PR DESCRIPTION
**Pull request by frheault**
After the new merge of PR #1812, most examples were not running.

Considering that before most trk saved and loaded by the tutorials were not valid, this PR is not only updating the function call, but also fixing the resulting TRK files involved.

### CODE REVIEW

**Comment by skoudoro** [comment]
Thank you for this @frheault! I will try them all because currently, the CI does not run the examples.

**Comment by Garyfallidis** [comment]
Coool! Thanks @frheault !

**Comment by frheault** [comment]
I know it is a lot of files, but since it is almost exactly the same lines changed in every examples/workflows I thought that it would be faster for all of us.

Any comments that apply to all, I will fix them similarly everywhere.
Also now I tested them and open the files in MI-Brain & Trackvis and they are valid !
image

**Comment by skoudoro** [comment]
When I generate the documentation, I got the following error with  `streamline_tools.py` tutorial:

```
*************************************************************
streamline_tools.py
*************************************************************
Dataset is already in place. If you want to fetch it again please first remove the folder C:\Users\skoudoro\.dipy\stanford_hardi
Dataset is already in place. If you want to fetch it again please first remove the folder C:\Users\skoudoro\.dipy\stanford_hardi
Dataset is already in place. If you want to fetch it again please first remove the folder C:\Users\skoudoro\.dipy\stanford_hardi
Dataset is already in place. If you want to fetch it again please first remove the folder C:\Users\skoudoro\.dipy\stanford_hardi
ERROR:root:Voxel space values higher than dimensions
Traceback (most recent call last):
  File "..\\..\\tools\\make_examples.py", line 166, in <module>
    run_script()
  File "..\\..\\tools\\make_examples.py", line 148, in run_script
    exec(f.read(), namespace)
  File "<string>", line 238, in <module>
  File "c:\users\skoudoro\devel\dipy\dipy\io\streamline.py", line 251, in save_trk
    save_tractogram(sft, filename, bbox_valid_check=bbox_valid_check)
  File "c:\users\skoudoro\devel\dipy\dipy\io\streamline.py", line 39, in save_tractogram
    raise ValueError('Bounding box is not valid in voxel space, cannot ' +
ValueError: Bounding box is not valid in voxel space, cannot save a valid file if some coordinates are invalid
```

**Comment by frheault** [comment]
@skoudoro I just fixed it. I guess it me that forgot to save or hit CTRL-Z by accident. The input space was VOX, not RASMM. Perfect catch using the value error, I guess my own code save me !

**Comment by skoudoro** [comment]
>  I guess my own code save me!

Nice,  Love it! I will try again to generate the doc, check the result and if Travis is Happy, will go ahead and merge it.

Does anyone want to have a look?

**Comment by skoudoro** [comment]
`bundle_extraction.py` example stopped to work. I do not think it is related to your PR but can you try to run it quickly and let me know. (Maybe it is my version of fury). Thank you

**Comment by frheault** [comment]
@skoudoro works fine on my side. I just resetup recently, nothing special that I remember (with vtk/fury)

**Comment by skoudoro** [comment]
Thank you @frheault, merging

**Pull request merged**
