### PR TITLE
WIP: CircleCI

### PR DESCRIPTION
**Pull request by arokem**
As discussed in a recent lab meeting, I am looking into whether we'd like to switch over to CircleCI. For now, I've activated CCI for my own fork, and builds are appearing here: https://github.com/arokem/dipy/pull/33

### CODE REVIEW

**Comment by arokem** [comment]
OK. Looks like I have the basic thing running here: https://circleci.com/gh/arokem/dipy/17

I've also managed to completely get rid of the nose dependency along the way.

Need to think what other things we'll need CircleCI to do for us (test on mac OS?) and how we decide whether this move is advantageous.

**Comment by skoudoro** [comment]
> Looks like I have the basic thing running here

Great!

> I've also managed to completely get rid of the nose dependency along the way.

That's a really good news! good job!

> Need to think what other things we'll need CircleCI to do for us

- Run the documentation examples and generate the documentation, that was the original goal.
- Indeed, Mac OsX, it will  goal

**Comment by arokem** [comment]
Ah yes -- doc builds. I'll get on that.

**Comment by skoudoro** [comment]
I forgot to talk about this PR in the online lab meeting. What is the status of this one?

**Comment by arokem** [comment]
It's not going so well :-( 

I've been trying to build the docs with this, but it times out on the second example (tracking quick-start). I think it fails because it needs to record some output every ten minutes, otherwise it assumes that something has stalled. See: https://circleci.com/gh/arokem/dipy/53

Next, I'm going to try to just run the test-suite, without building the docs.

**Comment by skoudoro** [comment]
it seems, there is an option to increase the timeout : `no_output_timeout: 1200`. but I do not know the limit and if it helps

**Comment by arokem** [comment]
OK - thanks! I'll give it a try after I have a run of the tests that
doesn't fail...

**Comment by skoudoro** [comment]
more useful information for the `no_output_timeout` :  https://support.circleci.com/hc/en-us/articles/360007188574-Build-has-hit-timeout-limit

**Comment by arokem** [comment]
Hmm. There seems to be an issue with testing Horizon (that XVFB is not mitigating for us, for some reason): https://circleci.com/gh/arokem/dipy/55

**Comment by arokem** [comment]
Closed in favor Azure pipelines solution...

**Pull request closed without merging**
