### PR TITLE
Refactor data module

### PR DESCRIPTION
**Pull request by arokem**
Here is a beginning of addressing #692 . 

For now, I have done the following: 

- Moved data files into their own directory
- Small changes in __init__.py to follow that 
- Major refactor of `fetcher.py`. Most `fetch_*` can be autogenerated from a few bits of information: a URL where the data is provided, names of files (both remotely and locally) and md5 hashes of the file contents for validation, etc.. I have written a function-generating function `_make_fetcher`, which does exactly that. 
- Beginning work to test all this. Still need to mock the URL request somehow, so that's the next thing I will do.

### CODE REVIEW

**Comment by arokem** [comment]
Looks like I didn't have to mock the URL after all - `pathname2url` solved that problem for me.

**Comment by arokem** [comment]
I believe this is ready for a review. 

Will go and clean up everything with PEP8, but feel free to take a look.

**Comment by MrBago** [comment]
@arokem this looks awesome. I like the design and organization and I'll give it a proper review in the next week or so.

**Comment by arokem** [comment]
Hey @MrBago - have you had a chance to take a look?

**Comment by Garyfallidis** [comment]
Resolve conflicts please. Do we really need a files directory?

**Comment by arokem** [comment]
Now rebased!

**Comment by arokem** [comment]
It got a bit cluttered with all of these files lying around, and was hard to see what are the files containing code

**Comment by MrBago** [comment]
I don't remember exactly what the issue was, but I believe dipy/data/tests
has issues if there is no files directory.

**Comment by Garyfallidis** [comment]
Looks good. Thx!

**Pull request merged**
