### PR TITLE
RF: Use cython imports instead of relying on extern

### PR DESCRIPTION
**Pull request by MarcCote**
Small refactoring as suggested by @matthew-brett (see comment https://github.com/nipy/dipy/pull/1076#issuecomment-294845381)

### CODE REVIEW

**Comment by matthew-brett** [comment]
Finishing up stdlib import removals at https://github.com/MarcCote/dipy/pull/10 .

**Comment by MarcCote** [comment]
Thanks.

**Comment by arokem** [comment]
Darn. Should've probably asked you to rebase on master before merging. Looks like this broke the master branch: https://travis-ci.org/nipy/dipy/jobs/224600749. Any idea how these things interact?

**Comment by arokem** [comment]
You're right. This is also relatively new, so might just be the precision wasn't set appropriately: https://github.com/nipy/dipy/pull/1231

To answer your question: yes, there is some randomness in that test: https://github.com/nipy/dipy/blob/master/dipy/reconst/tests/test_dki_micro.py#L88-L89

**Pull request merged**
