### PR TITLE
Remove the points added oustide of a mask. Fix the related tests.

### PR DESCRIPTION
**Pull request by czotti**
This PR is to address the issue #1661. 
I recreate a PR because I made a mistake during the rebase.

- It change the way points are added to a streamline if the point is outside the mask.
- I changed all the needed test.

### CODE REVIEW

**Comment by guaje** [comment]
Thanks, @czotti for your contribution. We're going to merge these changes.

**Comment by skoudoro** [comment]
+1, Thanks @czotti, Can you rebase this PR before I merge it

**Comment by czotti** [comment]
One test failing because it's unable to get python 3.5 from s3: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.5.tar.bz2

The second fails is due to Cython unable to compile: dipy.tracking.fbcmeasures.

As far as I know, it's not related to my commit no?

**Comment by skoudoro** [comment]
> One test failing because it's unable to get python 3.5 from s3

I just restarted this build

> As far as I know, it's not related to my commit no?

No, it is not related, DIPY is failing with the future Cython release, we have to fix it.

**Comment by skoudoro** [comment]
Merging, Thank you @czotti

**Pull request merged**
