### PR TITLE
Fix for fetcher files in Windows

### PR DESCRIPTION
**Pull request by manu-tej**
Fix for #1030 
'pathname2url' method is not needed in the test_fetcher.py

### CODE REVIEW

**Comment by manu-tej** [comment]
I will rebase it shortly

**Comment by arokem** [comment]
Great. That should also trigger a test on Travis (I just flipped the switch there back to "on").

**Comment by arokem** [comment]
I can run this on our buildbots, once you rebase this. Ping me when you've done that.

**Comment by manu-tej** [comment]
@arokem completed rebasing

**Comment by arokem** [comment]
Thank you. I've launched a test on one of the buildbots that was previously failing, from this branch here: http://nipy.bic.berkeley.edu/builders/dipy-bdist32-34/builds/249

**Comment by manu-tej** [comment]
@arokem: added the required modules

**Comment by manu-tej** [comment]
@arokem there is a good chance that this should fix the problem.

**Comment by arokem** [comment]
OK - thanks. This is the relevant Windows build testing that:
http://nipy.bic.berkeley.edu/builders/dipy-bdist32-34/builds/251

**Comment by manu-tej** [comment]
Meanwhile I will setup my own windows machine for testing.

**Comment by manu-tej** [comment]
@arokem : all the tests are passing. There are some residues which we don't need and I will remove them in next commit.
@ghoshbishakh : Can you have a look at it ? I hope I didn't break the download progress bar.

**Comment by arokem** [comment]
Yeah. Looks like there might be some un-needed imports now. Otherwise, LGTM.

**Comment by ghoshbishakh** [comment]
@manu-tej changes are in the tests so progressbar should be fine! :smile: thanks!

**Comment by ghoshbishakh** [comment]
@manu-tej the 4 commits can be squashed into to 2 to make it cleaner

**Comment by arokem** [comment]
No need to squash. I'll go ahead and merge.

**Comment by arokem** [comment]
Thanks both!

**Pull request merged**
