### PR TITLE
Re-entering conflict-free typos from deleted PR 1331

### PR DESCRIPTION
**Pull request by justbennet**
I believe these are all the corrections that are left that were not addressed by the documentation in the current master branch.  I am not able to run `make` on this, as that seems to want to download data and run dypy.  If there is a way to make _just_ the documentation and you can send me instructions and/or a link to the instructions for making just the docs, then I will be happy to give it a try.

Sorry for all the hassle this has caused.

### CODE REVIEW

**Comment by skoudoro** [comment]
Thanks for doing this @justbennet  and Thanks for the review @jchoude !

Unfortunately, there is no way to generate the documentation gallery without running examples but it should be easy to add a command for doing that.

Otherwise, everything else can be checked via `make api` and then `make html-after-examples`.

**Comment by jchoude** [comment]
@skoudoro Want to have a look, or we can merge? It is straight forward. I looked, all good. Was just waiting for the checks to finish, and they just did.

**Comment by justbennet** [comment]
@jchoude Did the annotation at the bottom work out OK?

I don't know how many people there are like me who don't run the software but do read the docs.  I help other people, and my laptop isn't really suitable to run Dipy.  I do use it to read documentation, though.  I think the software needed to make just the documenation would be supportable.  Up to you folks.

**Comment by skoudoro** [comment]
There is the same error on these 3 files:
* [reconst_csa.py](https://github.com/nipy/dipy/blob/master/doc/examples/reconst_csa.py#L129)
* [workflow_creation.py](https://github.com/nipy/dipy/blob/master/doc/examples/workflow_creation.py#L128)
* [combined_workflow_creation.py](https://github.com/nipy/dipy/blob/master/doc/examples/combined_workflow_creation.py#L141)

It would be great if you can you remove all spaces from these files @justbennet  :-)

After that, we can merge it. 

Thanks !

**Comment by justbennet** [comment]
I don't understand.  I did not touch those file at all.

**Comment by justbennet** [comment]
I touched one file only, doc/examples/gradients_spheres.py

**Comment by jchoude** [comment]
I think that @skoudoro meant that, at the same time, if you could additionnally fix it in the other files, he would be appreciative :)

And I understand your comment about just generating the documentation without running everything. The situation is that all images and screenshots are generated directly using the software, so, for the example to completly render, they need to do some processing.

**Comment by skoudoro** [comment]
Exactly, Thanks @jchoude , and sorry if I was not clear.

**Comment by justbennet** [comment]
Ah.  OK.  What spaces?  The trailing space at the end of those files?

**Comment by justbennet** [comment]
I believe I did as you requested.  Sorry for the delay.  I am at a different machine and had to reclone the repository.

**Comment by jchoude** [comment]
No problem! Thanks a lot for your patience with us!

I'm just waiting on the CI to finish.

**Comment by jchoude** [comment]
I generated the rst files locally, and the all render correctly. Merging!

Thanks @justbennet for your work!

**Comment by justbennet** [comment]
You're welcome.

**Pull request merged**
