### PR TITLE
BF: Convert floating point values to ints for array indexing

### PR DESCRIPTION
**Pull request by omarocegueda**
Fixes array indexing with floating point values shown as warnings here:
http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/646/steps/shell_9/logs/stdio

### CODE REVIEW

**Comment by arokem** [comment]
LGTM. Thanks for doing this!

**Comment by omarocegueda** [comment]
Thanks Ariel!, I tried to run `try_branch` on this but apparently there's a recent bug in `sqlalchemy` module loaded by `buildbot`:
>File "/home/omar/anaconda2/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 43, in <module>
    class RefCollection(util.MemoizedSlots):
AttributeError: 'module' object has no attribute 'MemoizedSlots'

I just reported the issue in sqlalchemy. Meanwhile we will need to wait to see if this solves the issues.

**Comment by arokem** [comment]
Which bot is this happening on?

**Comment by omarocegueda** [comment]
the problem is on my side when I run `try_branch`. I checked and the error message is correct, `MemoizedSlots` is not defined in utils. It's being quite a long time since the last time I ran `try_branch`, many things must have changed since then.

**Comment by matthew-brett** [comment]
Omar - did you already update buildbot?

**Comment by arokem** [comment]
try_branch works for me without a hitch with a fairly recent (yesterday)
buildbot. Since this is already merged, let's just see what the bots say...

**Comment by omarocegueda** [comment]
Yes, I installed it today (my computer "died" recently, and I had to
re-install everything from scratch)

On Thu, Nov 26, 2015 at 3:41 PM, Matthew Brett <notifications@github.com>
wrote:

> Omar - did you already update buildbot?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nipy/dipy/pull/792#issuecomment-159996734>.
>



-- 
"Cada quien es dueño de lo que calla y esclavo de lo que dice"
-Proverbio chino.
"We all are owners of what we keep silent and slaves of what we say"
-Chinese proverb.

http://www.cimat.mx/~omar

**Comment by matthew-brett** [comment]
On Thu, Nov 26, 2015 at 1:53 PM, Omar Ocegueda <notifications@github.com>
wrote:

> Yes, I installed it today (my computer "died" recently, and I had to
> re-install everything from scratch)
>

Did you install buildbot in anaconda?  Any luck if you use system python
and pip instead?

**Comment by omarocegueda** [comment]
My guess is that it is a bug from sqlalchemy, current version is 1.0.9,
just released October 20th.

On Thu, Nov 26, 2015 at 3:48 PM, Ariel Rokem <notifications@github.com>
wrote:

> try_branch works for me without a hitch with a fairly recent (yesterday)
> buildbot. Since this is already merged, let's just see what the bots say...
>
> On Thu, Nov 26, 2015 at 1:41 PM, Matthew Brett <notifications@github.com>
> wrote:
>
> > Omar - did you already update buildbot?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nipy/dipy/pull/792#issuecomment-159996734>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nipy/dipy/pull/792#issuecomment-159997265>.
>



-- 
"Cada quien es dueño de lo que calla y esclavo de lo que dice"
-Proverbio chino.
"We all are owners of what we keep silent and slaves of what we say"
-Chinese proverb.

http://www.cimat.mx/~omar

**Comment by omarocegueda** [comment]
I did:
*pip install buildbot*

and it installed it within the anaconda2 bin folder:

*omar@julia:~/opt$ which buildbot*
/home/omar/anaconda2/bin/buildbot

because if I try with conda:

*omar@julia:~/opt$ conda install buildbot*
Fetching package metadata: ....
Error: No packages found in current linux-64 channels matching: buildbot

You can search for this package on anaconda.org with

    anaconda search -t conda buildbot

I'm not sure if it is safe to just select one of the packages shown by
*anaconda
search -t conda buildbot*

On Thu, Nov 26, 2015 at 3:55 PM, Jesus-Omar Ocegueda-Gonzalez <
jomaroceguedag@gmail.com> wrote:

> My guess is that it is a bug from sqlalchemy, current version is 1.0.9,
> just released October 20th.
>
> On Thu, Nov 26, 2015 at 3:48 PM, Ariel Rokem <notifications@github.com>
> wrote:
>
>> try_branch works for me without a hitch with a fairly recent (yesterday)
>> buildbot. Since this is already merged, let's just see what the bots
>> say...
>>
>> On Thu, Nov 26, 2015 at 1:41 PM, Matthew Brett <notifications@github.com>
>> wrote:
>>
>> > Omar - did you already update buildbot?
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/nipy/dipy/pull/792#issuecomment-159996734>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/nipy/dipy/pull/792#issuecomment-159997265>.
>>
>
>
>
> --
> "Cada quien es dueño de lo que calla y esclavo de lo que dice"
> -Proverbio chino.
> "We all are owners of what we keep silent and slaves of what we say"
> -Chinese proverb.
>
> http://www.cimat.mx/~omar
>



-- 
"Cada quien es dueño de lo que calla y esclavo de lo que dice"
-Proverbio chino.
"We all are owners of what we keep silent and slaves of what we say"
-Chinese proverb.

http://www.cimat.mx/~omar

**Comment by matthew-brett** [comment]
Unfortunately, because the package authors don't support conda, generally, you always end up having to first replicate the problem using standard tools like pip, outside a conda environment, and depending on the result either submitting a bug report to conda or to the package maintainer.

**Comment by omarocegueda** [comment]
I see!, another point in favour of using standard tools... oh! well "the
lazy work twice as hard"...


On Thu, Nov 26, 2015 at 4:06 PM, Matthew Brett <notifications@github.com>
wrote:

> Unfortunately, because the package authors don't support conda, generally,
> you always end up having to first replicate the problem using standard
> tools like pip, outside a conda environment, and depending on the result
> either submitting a bug report to conda or to the package maintainer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nipy/dipy/pull/792#issuecomment-159998539>.
>



-- 
"Cada quien es dueño de lo que calla y esclavo de lo que dice"
-Proverbio chino.
"We all are owners of what we keep silent and slaves of what we say"
-Chinese proverb.

http://www.cimat.mx/~omar

**Comment by omarocegueda** [comment]
Alright, now I'm following Matthew's recommendations instead of anaconda (thanks for creating this page!):
https://matthew-brett.github.io/pydagogue/installing_on_debian.html

`buildbot` works well with the latest version of `sqlalchemy`.

**Comment by matthew-brett** [comment]
Inspired, I updated that page for the newest pip versions :  https://matthew-brett.github.io/pydagogue/installing_on_debian.html

**Comment by omarocegueda** [comment]
Oh! wow, I just "discovered" that there are many more useful tutorials in
"Pydagogue" =o. I liked this (slightly modified) sentence:

So – please – invest an hour of your life to understand this stuff.
Concentrate, go slowly, make sure you get it. In return for an hour of your
life, you will get many happy years for which *<insert development tool
name here>* will appear in its true form, both beautiful and useful.

Thanks! =)

On Sat, Nov 28, 2015 at 3:01 AM, Matthew Brett <notifications@github.com>
wrote:

> Inspired, I updated that page for the newest pip versions :
> https://matthew-brett.github.io/pydagogue/installing_on_debian.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nipy/dipy/pull/792#issuecomment-160265375>.
>



-- 
"Cada quien es dueño de lo que calla y esclavo de lo que dice"
-Proverbio chino.
"We all are owners of what we keep silent and slaves of what we say"
-Chinese proverb.

http://www.cimat.mx/~omar

**Pull request merged**
