### PR TITLE
Revert "Added File Menu element to viz.ui"

### PR DESCRIPTION
**Pull request by arokem**
So sorry! I seem to have merged the wrong PR

### CODE REVIEW

**Comment by karandeepSJ** [comment]
@ranveeraggarwal  @dmreagan @Garyfallidis Do we need to revert this or is the FileMenu good?

**Comment by dmreagan** [comment]
I'd like to merge this to revert #1570, but it looks like it is failing a test because it doesn't include the bugfix from #1574. What's the correct way to proceed?

**Comment by karandeepSJ** [comment]
They failed because this PR was made before the fix was merged. Is there any way of running travis again?

**Comment by dmreagan** [comment]
We just restarted the failing Travis machine, but I'm guessing it will fail again. I think we need @arokem to rebase this, but keep the two lines from the bugfix in #1574.

**Comment by dmreagan** [comment]
Can you take a look at this, @arokem?

**Comment by arokem** [comment]
Closed in favor of #1590. Hopefully that should pass now, I just implemented the fix from #1574 there as well, and that seems to have been the failing test here.

**Pull request closed without merging**
