### PR TITLE
BF: Should fix #1037

### LINKED ISSUE #1037: tracking.interfaces imports SlowAdcOpdfModel, but it is not defined
See: http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/758/steps/shell_9/logs/stdio

`dipy/tracking/interfaces.py` has this line:

```
from ..reconst.shm import (SlowAdcOpdfModel, MonoExpOpdfModel, QballOdfModel,
```

but `dipy.reconst.shm` does not define `SlowAdcOpdfModel` .

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by matthew-brett** [comment]
Would you mind doing a `try_branch.py` on this one for `dipy-py2.6-32`

**Comment by arokem** [comment]
http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/759

**Comment by arokem** [comment]
http://nipy.bic.berkeley.edu/builders/dipy-py2.6-32/builds/760

**Comment by arokem** [comment]
This might fix the specific bug, but should we remove this module altogether? It seems like unused cruft to me, and has had that "ThisIsBroken" warning since forever.

**Comment by arokem** [comment]
Any thoughts here? Should we remove this module altogether?

**Comment by arokem** [comment]
I believe this is superseded by https://github.com/nipy/dipy/pull/1056

Closing

**Pull request closed without merging**
