### PR TITLE
Color Picker element for viz.ui

### PR DESCRIPTION
**Pull request by karandeepSJ**
This PR implements a Color Picker based on the HSV color model. It consists of a vertical bar that selects the hue and a square that selects the saturation and value for the selected hue.  
The horizontal direction of the square corresponds to saturation and the vertical axis to value.
There is a small ring inside the square to track the colors selected. The colors in the square get updated whenever the hue is changed.
Refer to my [blog post](https://blogs.python-gsoc.org/karandeep-singh-juneja/2018/07/25/colors-and-animations/) to know about the HSV color model and how I implemented this color picker.

colorpicker

### CODE REVIEW

**Comment by karandeepSJ** [comment]
What tests should I write for this? It is very difficult to check whether the right colors are being selected because of the precision in coordinates required.

**Comment by dmreagan** [comment]
This is cool. A few quick thoughts:

- It should respond to clicks in addition to drags.
- There should be a little rectangle showing the current hue position
- There should be a simple way for the user to get the color in RGB as (R, G, B)

**Comment by skoudoro** [comment]
Hi @karandeepSJ,

Can you move this PR on this repo : https://github.com/fury-gl/fury ?

Thank you!

**Comment by skoudoro** [comment]
Closing. This PR was moved to https://github.com/fury-gl/fury/pull/20

**Pull request closed without merging**
