### PR TITLE
ENH: Remove deprecated SH bases

### PR DESCRIPTION
**Pull request by jhlegarreta**
Remove deprecated SH bases.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@arokem @skoudoro as discussed in the dev meeting this morning. I guess we are aware of the fact that dependent software developers will need to adapt to the change.

**Comment by arokem** [comment]
Might be worth documenting this one in https://github.com/nipy/dipy/blob/master/doc/api_changes.rst.

**Comment by jhlegarreta** [comment]
Thanks for the review @arokem. Done in 68640a3.

**Comment by skoudoro** [comment]
Hi @jhlegarreta,
 
Can you rebase? I think you forgot to remove some `DeprecationWarning` test too. Thank you for this.

**Comment by jhlegarreta** [comment]
@skoudoro I'd dare to say that I h[ad removed them](https://github.com/nipy/dipy/pull/1905/files#diff-3e4977fe011c140316eddd2a0bb433beL390).

Rebased on master and push-forced.

**Comment by skoudoro** [comment]
it seems you forgot the one [here](https://github.com/nipy/dipy/blob/418c6f3ce86a3270ef1baf1f25c7602fb0b2a073/dipy/reconst/tests/test_shm.py#L379) and [here](https://github.com/nipy/dipy/blob/master/dipy/direction/tests/test_prob_direction_getter.py#L62), this is why Travis is failing.

**Comment by jhlegarreta** [comment]
@skoudoro my bad. Sorry for the oversight. 68e5dd7 should address all cases. Rebased and push forced.

**Comment by jhlegarreta** [comment]
Just one particular Travis build is failing. I guess we are experiencing this in other PRs.

**Comment by skoudoro** [comment]
it was a weird error, I restarted this matrix to make sure that's is reproducible. I do not see it on other PR

**Comment by skoudoro** [comment]
Thank you @jhlegarreta, merging!

**Pull request merged**
