### PR TITLE
MRG:Data off dropbox

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by arokem** [comment]
Hey @Garyfallidis : I don't have the "icomoon.tar.gz" file! Could you please share that with me?

**Comment by arokem** [comment]
Oh - scratch that. I seem to have saved a copy of these icons elsewhere!

**Comment by arokem** [comment]
This is ready to go from my point of view. I have verified that all these data-sets can be retrieved from their new locations using the refactored fetcher functions.

**Comment by Garyfallidis** [comment]
Great thanks!

**Pull request merged**
