### PR TITLE
miscellaneous Python 3 compatibility problem fixes in fvtk

### PR DESCRIPTION
**Pull request by grlee77**
I was testing out `fvtk` (which is very nice by the way!) and encountered a number of small issues related to integer division, etc on Python 3 in both `dipy.viz` and a few of the examples.

I can omit b99d107227058b7e8bc58c8f1f64810f69d74235 if you don't want that one here.  It is related to future VTK 7.0 compatibility which I will discuss in a separate issue.

### CODE REVIEW

**Comment by arokem** [comment]
Wait, VTK now works on Python 3?! That's incredible!

**Comment by grlee77** [comment]
Yes, very soon!  I encountered one error compiling using VTK 7.0 RC2, but got a patch for it accepted into the release branch by kitware so hopefully all will be well come the official 7.0 release.

**Comment by Garyfallidis** [comment]
Thank you so much for doing this @grlee77 :dancers: 
It's great to know that the new dipy.viz works in VTK 7.

**Comment by Garyfallidis** [comment]
And thank you of course for your corrections in this PR. All looks good! Have a nice day. :+1:

**Comment by arokem** [comment]
Should we set up a test bot with this version of VTK? Is it even out yet?

**Comment by Garyfallidis** [comment]
I think it's too early. I cannot find any available packages for VTK 7. Let's put a reminder for a month from now. They should start appearing soon. VTK 7 has some crazy features too. It is compatible with OpenGL ES!!!  There is going to be a webinar speaking about the new features in two days from now https://blog.kitware.com/vtk-7-0-release-webinar

**Comment by grlee77** [comment]
thanks for the quick merge!  I am not sure of the exact VTK7 release date, but RC2 was released Jan 14 and the blog post about it stated "in a few weeks time", so definitely soon.

**Comment by matthew-brett** [comment]
VTK7 released today: https://blog.kitware.com/vtk-7-0-0/

**Pull request merged**
