### PR TITLE
Modifications for building docs with python3

### LINKED ISSUE #912: Unable to build documentation with Python 3
`make html` only works with python 2 and when dipy is installed with python 2

### PR DESCRIPTION
**Pull request by ghoshbishakh**
Change apigen.py for python3 support
And minor PEP8 changes
fixes #912

### CODE REVIEW

**Comment by arokem** [comment]
Nice! But documentation still does not build on Python 3 with this fix. Still need to also adjust this file to be Python 3 compliant: https://github.com/nipy/dipy/blob/master/doc/sphinxext/github.py

This line, for starters: https://github.com/nipy/dipy/blob/master/doc/sphinxext/github.py#L39

(that's where I get an error raised)

**Comment by ghoshbishakh** [comment]
I don't get it on make api or make html
Any suggestions how should I test it?

**Comment by arokem** [comment]
I am not sure. Could it be that your system is getting the `github` sphinx extension from somewhere else?

**Comment by arokem** [comment]
Either way, it's still not Python 3 compliant. 

Try: 

    cd ~/source/dipy/doc/sphinxext
    python -c"import github"

**Comment by ghoshbishakh** [comment]
@arokem yes I will fix that file. I have to check why I am not getting the error.

**Comment by ghoshbishakh** [comment]
@arokem sorry my bad. I was using python2 sphinx as default. I found that numpydoc extension also crashes. I think removing it from the sphinxext folder will be better as we can use the lastest numpydoc without shipping an older version. What do you recommend?

**Comment by arokem** [comment]
You can also get python 3 compliant versions of all these here: https://github.com/uwescience/shablona/tree/master/doc/sphinxext

**Comment by ghoshbishakh** [comment]
@arokem okey then I will include those.

**Comment by Garyfallidis** [comment]
Looks good. Thanks @ghoshbishakh 
Is there anything left on this PR? If not I will be happy to merge it.

**Comment by ghoshbishakh** [comment]
@Garyfallidis Not much is left. But I have not been able to test it completely with python3 as it takes a long time. You may merge it as I can make patches later also.

**Comment by Garyfallidis** [comment]
Why does it take a long time?

**Comment by ghoshbishakh** [comment]
@Garyfallidis Because I have only 4GB RAM and the build process requires about 16GB. And using swap it takes about 20 hours to build the entire doc.

**Comment by Garyfallidis** [comment]
I think there are only a few examples that need more memory than usual. DKI and Life. You may want to disable them by commenting them at doc/examples/valid_examples.txt
Here is what I think may require more memory.
linear_fascicle_evaluation.py
reconst_dki.py
Let me know if that helped.

**Comment by ghoshbishakh** [comment]
@Garyfallidis ok. I will build it and post a link here.

**Comment by ghoshbishakh** [comment]
I am getting this error:

```
segment_extending_clustering_framework.py
segment_clustering_features.py
Nb. clusters: 4
Cluster sizes: <map object at 0x7fa07c621588>
Nb. clusters: 4
Cluster sizes: <map object at 0x7fa07d5eb3c8>
Traceback (most recent call last):
  File "../tools/make_examples.py", line 122, in <module>
    exec(open(script).read(), namespace)
  File "<string>", line 172, in <module>
IndexError: too many indices for array
Makefile:122: recipe for target 'rstexamples-stamp' failed
make: *** [rstexamples-stamp] Error 1
make html  1442.06s user 18.58s system 134% cpu 18:07.87 total

```

screenshot from 2016-07-13 15-37-10

**Comment by Garyfallidis** [comment]
Hi @MarcCote have you seen this? Any ideas?

**Comment by ghoshbishakh** [comment]
I ran the code for  segment_clustering_features.py  separately and I get this:

```
python segment_clustering_features.py 
Nb. clusters: 4
Cluster sizes: <map object at 0x7faf5bcc55f8>
Nb. clusters: 4
Cluster sizes: <map object at 0x7faf5df22358>
Traceback (most recent call last):
  File "segment_clustering_features.py", line 172, in <module>
    fvtk.add(ren, fvtk.point(centers[:, 0, :], colormap_full, point_radius=0.2))
IndexError: too many indices for array

```

**Comment by MarcCote** [comment]
@ghoshbishakh: @Garyfallidis just told me about your issue with `segment_clustering_features.py`. I just made a PR on your branch. That should resolve the issue. Basically, since in Python3 `map(...)` returns a generator, I had to cast them into list objects.

**Comment by ghoshbishakh** [comment]
What did just happen? I merged @MarcCote 's PR and pulled it locally and then made a push and this happened. :worried:

**Comment by ghoshbishakh** [comment]
@MarcCote seems I have made a successful reset! Can you somehow make the PR again?

**Comment by arokem** [comment]
You might want to both be rebased on top of current master before trying
again :-)

**Comment by ghoshbishakh** [comment]
As @arokem suggested, I rebased on master and made a push. @MarcCote can you send the PR now? Lets see if it works out properly this time.

**Comment by ghoshbishakh** [comment]
That PR solved that issue @MarcCote :smile: 
But now I am getting another error:
```
Computing tensors...
Computing worst-case/best-case SNR using the corpus callosum...
Noise standard deviation sigma=  9.83112897825
SNR for the b=0 image is : 42.0959119804
SNR for direction 58   [ 0.98875  0.1177  -0.09229] is : 5.47338194103
SNR for direction 57   [-0.05039    0.99871    0.0054406] is : 23.9479488745
SNR for direction 126   [-0.11825  -0.039925  0.99218 ] is : 24.0116089426
streamline_formats.py
/home/bishakh/projects/dipy/dipy/data/files/tracks300.trk
Traceback (most recent call last):
  File "../tools/make_examples.py", line 122, in <module>
    exec(open(script).read(), namespace)
  File "<string>", line 54, in <module>
  File "/home/bishakh/projects/dipy/dipy/io/dpy.py", line 70, in __init__
    ['0.0.1'], 'Dpy Version Number')
  File "/usr/lib/python3.5/site-packages/tables/_past.py", line 35, in oldfunc
    return obj(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/tables/file.py", line 1152, in create_array
    obj=obj, title=title, byteorder=byteorder)
  File "/usr/lib/python3.5/site-packages/tables/array.py", line 188, in __init__
    byteorder, _log)
  File "/usr/lib/python3.5/site-packages/tables/leaf.py", line 262, in __init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "/usr/lib/python3.5/site-packages/tables/node.py", line 267, in __init__
    self._v_objectid = self._g_create()
  File "/usr/lib/python3.5/site-packages/tables/array.py", line 205, in _g_create
    raise TypeError("Array objects cannot currently deal with void, "
TypeError: Array objects cannot currently deal with void, unicode or object arrays
Closing remaining open files:fornix.dpy...done
Makefile:122: recipe for target 'rstexamples-stamp' failed
make: *** [rstexamples-stamp] Error 1
make html  1588.85s user 1668.44s system 216% cpu 25:02.59 total
```

screenshot from 2016-07-24 20-26-25

**Comment by ghoshbishakh** [comment]
Here is the output if I run streamline_formats.py separately:
```
bishakh@bisu-arch ~/projects/dipy/doc/examples (git)-[docsPy3] % python streamline_formats.py 
/home/bishakh/projects/dipy/dipy/data/files/tracks300.trk
Traceback (most recent call last):
  File "streamline_formats.py", line 54, in <module>
    dpw = Dpy('fornix.dpy', 'w')
  File "/home/bishakh/projects/dipy/dipy/io/dpy.py", line 70, in __init__
    ['0.0.1'], 'Dpy Version Number')
  File "/usr/lib/python3.5/site-packages/tables/_past.py", line 35, in oldfunc
    return obj(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/tables/file.py", line 1152, in create_array
    obj=obj, title=title, byteorder=byteorder)
  File "/usr/lib/python3.5/site-packages/tables/array.py", line 188, in __init__
    byteorder, _log)
  File "/usr/lib/python3.5/site-packages/tables/leaf.py", line 262, in __init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "/usr/lib/python3.5/site-packages/tables/node.py", line 267, in __init__
    self._v_objectid = self._g_create()
  File "/usr/lib/python3.5/site-packages/tables/array.py", line 205, in _g_create
    raise TypeError("Array objects cannot currently deal with void, "
TypeError: Array objects cannot currently deal with void, unicode or object arrays
Closing remaining open files:fornix.dpy...done
```

**Comment by ghoshbishakh** [comment]
looks like changing

```
self.version = self.f.createArray(self.f.root, 'version',
                                              ['0.0.1'], 'Dpy Version Number')
```

to 
```
self.version = self.f.createArray(self.f.root, 'version',
                                              [b"0.0.1"], 'Dpy Version Number')
```

fixes it.

Got some clue from here:
https://github.com/PyTables/PyTables/commit/b7c143054a5d63f1ebda512f470d667de5ebc764

**Comment by ghoshbishakh** [comment]
@arokem can you suggest me if I should make that change in the string in this PR?

**Comment by arokem** [comment]
Where is this change implemented? In `dipy/io/dpy.py`? Does it work with Python 2 when you implement this change?

**Comment by ghoshbishakh** [comment]
@arokem yes the change is in `dipy/io/dpy.py`

And yes it works in both python2 and 3 and the output is:
```
bishakh@bisu-arch ~/projects/dipy/doc/examples (git)-[docsPy3] % python2 streamline_formats.py
/home/bishakh/projects/dipy/dipy/data/files/tracks300.trk
300
5
bishakh@bisu-arch ~/projects/dipy/doc/examples (git)-[docsPy3] % python streamline_formats.py 
/home/bishakh/projects/dipy/dipy/data/files/tracks300.trk
300
5
```

**Comment by arokem** [comment]
Then yes - I say we should include it in this PR. @Garyfallidis : any thoughts here?

**Comment by arokem** [comment]
Sorry - let me walk back that last comment. Thinking about this for one more second: I think this should be a separate PR. In particular, I would like to see a test that fails on current master, and is fixed when this change is introduced.

**Comment by arokem** [comment]
That should make for a really small PR, which we can merge quickly. Then, you can rebase this current PR on top of that change and move ahead with it. How does that sound?

**Comment by ghoshbishakh** [comment]
@arokem Ok I am making a separate PR quickly

**Comment by arokem** [comment]
OK - now that #1100 is merged, you can rebase this one and keep going here.

**Comment by ghoshbishakh** [comment]
Now there is a problem with restore_dti.py

```
restore_dti.py
Traceback (most recent call last):
  File "../tools/make_examples.py", line 122, in <module>
    exec(open(script).read(), namespace)
  File "<string>", line 39, in <module>
NameError: name 'reload' is not defined
make: *** [Makefile:122: rstexamples-stamp] Error 1
make html  6893.82s user 29.25s system 244% cpu 47:13.14 total
```

**Comment by ghoshbishakh** [comment]
except for issue #1104 everything works fine now! I have made a PR #1105 to solve that.

**Comment by ghoshbishakh** [comment]
@arokem now this works with all examples enabled except :
1. linear_fascicle_evaluation.py
2. reconst_dki.py

**Comment by arokem** [comment]
Why are you not running these? The DKI example does rely on downloading a large amount of data (we need data with multiple b-values...). I just ran it on Python 3 on my laptop and it runs fine. 

The LiFE example (`linear_fascicle_evalutation.py`) doesn't require large amounts of data, or large amounts of RAM, so you should try running it. I can't get it to run on my machine, because I don't have VTK installed on my Python 3 installation, but if you have VTK installed, you should try running that.

**Comment by ghoshbishakh** [comment]
I ran LiFE example and it does take a lot of ram and my pc is stuck now. I
will let it run for tonight and check the result tomorrow morning.

Just out of curiosity.. I noticed some examples use all the 4 cores to
process and run considerably fast while some others make use of only one
core and take a lot of time.
Why is this and can this be improved?

**Comment by arokem** [comment]
Did you run the `streamline_tools` example beforehand?

If you have the file 'lr-superiorfrontal.trk' in place already (that is,
after tracking) the LiFE example takes (on my machine) about 3 minutes to
run, and takes about 38 MB RAM.

As for full utilization of cpu: some of our code already uses
multiprocessing, and some still needs to be rewritten to use
multiprocessing :-)

**Comment by ghoshbishakh** [comment]
@arokem I just ran the example separately this time and it worked.
```
bishakh@bisu-arch ~/projects/dipy/doc/examples (git)-[docsPy3] % python linear_fascicle_evaluation.py
Dataset is already in place. If you want to fetch it again please first remove the folder /home/bishakh/.dipy/stanford_hardi 
Dataset is already in place. If you want to fetch it again please first remove the folder /home/bishakh/.dipy/stanford_hardi 
Dataset is already in place. If you want to fetch it again please first remove the folder /home/bishakh/.dipy/stanford_hardi 
Dataset is already in place. If you want to fetch it again please first remove the folder /home/bishakh/.dipy/stanford_hardi 
Dataset is already in place. If you want to fetch it again please first remove the folder /home/bishakh/.dipy/stanford_hardi 
Camera Position (40.00,52.50,330.80)
Camera Focal Point (40.00,52.50,37.50)
Camera View Up (0.00,1.00,0.00)
-------------------------------------
Camera New Position (-1.00,0.00,0.00)
Camera New Focal Point (0.00,0.00,0.00)
Camera New View Up (0.00,0.00,1.00)
python linear_fascicle_evaluation.py  285.87s user 16.08s system 19% cpu 25:44.50 total
```

**Comment by arokem** [comment]
Excellent! I think this is probably ready to go then, right? 

Anyone else want to take a look?

**Comment by ghoshbishakh** [comment]
@arokem yes it is working perfectly. Let others take a look for a couple of days.

**Pull request merged**
