### PR TITLE
BF: Import Streamlines object directly from nibabel.

### LINKED ISSUE #1366: Circular imports in dipy.tracking.utils?
## Description
Reported by @peterneher on gitter: `import dipy.tracking.utils` seems to result in an error, possibly 
because of a circular import (see below).

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example: 

```
In [1]: import dipy.tracking.utils as ut
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-758b4154125b> in <module>()
----> 1 import dipy.tracking.utils as ut

~/source/dipy/dipy/tracking/utils.py in <module>()
     62 import numpy as np
     63 from numpy import (asarray, ceil, dot, empty, eye, sqrt)
---> 64 from dipy.io.bvectxt import ornt_mapping
     65 from dipy.tracking import metrics
     66 from dipy.tracking.vox2track import _streamlines_in_mask

~/source/dipy/dipy/io/__init__.py in <module>()
      3 
      4 from .gradients import read_bvals_bvecs
----> 5 from .dpy import Dpy
      6 from .bvectxt import (read_bvec_file, ornt_mapping, reorient_vectors,
      7                       reorient_on_axis, orientation_from_string,

~/source/dipy/dipy/io/dpy.py in <module>()
     12 import h5py
     13 
---> 14 from dipy.tracking.streamline import Streamlines
     15 
     16 # Make sure not to carry across setup module from * import

~/source/dipy/dipy/tracking/streamline.py in <module>()
     10 from dipy.tracking.streamlinespeed import length
     11 from dipy.tracking.streamlinespeed import compress_streamlines
---> 12 import dipy.tracking.utils as ut
     13 from dipy.tracking.utils import streamline_near_roi
     14 from dipy.core.geometry import dist_to_corner

AttributeError: module 'dipy.tracking' has no attribute 'utils'

```

### PR DESCRIPTION
**Pull request by arokem**
Fixes #1366

### CODE REVIEW

**Comment by skoudoro** [comment]
Thanks @arokem ! it works fine for me too so I merge

**Comment by arokem** [comment]
The thing that confuses me is why no tests were failing on Travis before... anyone have any ideas?

**Comment by skoudoro** [comment]
At the moment, no idea, this confuses me too

**Comment by arokem** [comment]
@peterneher: what OS are you on? I am on a mac -- maybe that's the source of the difference?

**Pull request merged**
