### PR TITLE
WIP: A lightweight UI for medical visualizations based on VTK-Python

### PR DESCRIPTION
**Pull request by ranveeraggarwal**
This PR introduces a VTK-based UI. All the UI elements are within the same window as the other elements. We do not use Qt/GTK or any other UI library apart from VTK. More information about the project here: http://ranveeraggarwal.com/subblogs/gsoc-16/

### CODE REVIEW

**Comment by MarcCote** [comment]
Note that this PR builds on top of PR #1098 (might need to rebase at some point).

**Comment by skoudoro** [comment]
Hi @ranveeraggarwal  and @MarcCote, What should we do with this PR? Almost everything seems already to be in DIPY so should we close it?  Do you plan to create a PR for the orbital menu @ranveeraggarwal?

**Comment by ranveeraggarwal** [comment]
@skoudoro IMO, let's close this after all the sub-PRs are done.
I will be making a follower menu PR this weekend.

**Comment by ranveeraggarwal** [comment]
@skoudoro yes, I suppose so.

**Comment by skoudoro** [comment]
Hi @ranveeraggarwal ,

Can you move this old PR on this fury repo : https://github.com/fury-gl/fury ?

Thank you!

**Comment by ranveeraggarwal** [comment]
@skoudoro sure, let me figure out how to - never done this before.

**Comment by skoudoro** [comment]
Closing in favor of a new PR in [FURY](https://github.com/fury-gl/fury/pulls)

**Pull request closed without merging**
