### PR TITLE
Fixed the Progit book link in the docs

### PR DESCRIPTION
**Pull request by ShreyasFadnavis**
Patch to #1461

### CODE REVIEW

**Comment by arokem** [comment]
This seems to have convolved two PRs. 

To see our recommended git workflow, please refer to the documentation: http://nipy.org/dipy/devel/gitwash/index.html

In particular, please use feature branches, instead of working on `master`, to avoid this kind of situation.

**Comment by ShreyasFadnavis** [comment]
@arokem Thank you! Will do that right away..

**Comment by arokem** [comment]
Sorry - just now checked this. The old link works just fine. The new link doesn't. 

Closing for now.

**Comment by arokem** [comment]
Whoops. Looks like I am wrong. The new link is correct. 

However, this PR is off of your master branch, and has too many commits at this point. Could you open a new PR off of a feature branch, with just one single commit fixing the link? I'll merge that if you create it.

**Pull request closed without merging**
