### PR TITLE
Fix bug in actor.label

### LINKED ISSUE #1551: Actor.label not working anymore
## Description
When running the minimal example from the Actor.label documentation is results in a black window without any text.

## Way to reproduce
```
from dipy.viz import window, actor
ren = window.Renderer()
l = actor.label(text='Hello')
ren.add(l)
window.show(ren)
```

### PR DESCRIPTION
**Pull request by wasserth**
Closes #1551

### CODE REVIEW

**Comment by dmreagan** [comment]
@karandeepSJ I couldn't figure out how to officially request a review from you, but please take a look at this PR.

**Comment by karandeepSJ** [comment]
Looks good

**Comment by Garyfallidis** [comment]
@wasserth thanks!

**Comment by Garyfallidis** [comment]
This was very helpful. 👍

**Pull request merged**
