### PR TITLE
Examples update 

### PR DESCRIPTION
**Pull request by skoudoro**
Follow-up of #2016 and #2020. All examples will use `get_fnames`, `load_nifti` and `save_nifti` to handle the I/O. This is more explicit for the basic user.

### CODE REVIEW

**Comment by arokem** [comment]
Looks great! I think this will really help new users adapt this to their data.

**Comment by skoudoro** [comment]
Ok, all examples have been updated, sorry for this huge PR. 

I think this is ready to go, but I will generate the documentation on my laptop a last time.

**Comment by skoudoro** [comment]
Documentation generation done without any problem. This PR is ready to go!

**Comment by arokem** [comment]
Did you have a chance to follow up on #2009 with updates in that example and the relevant changes in dipy.data?

**Comment by arokem** [comment]
BTW: I am experimenting with Github Actions for documentation building. Check out the PR on my fork here: https://github.com/arokem/dipy/pull/35. The build actually seems to work fine. It hasn't completed yet, but the failures so far are usually because it needs more optional dependencies built. I am not sure we want this to run for every PR, but I think that we can set this up to run as a cron job on master and check it on a ~weekly basis.

**Comment by skoudoro** [comment]
> Did you have a chance to follow up on #2009 with updates in that example and the relevant changes in dipy.data?

done in 0357684

>  I am experimenting with Github Actions for documentation building. Check out the PR on my fork here: arokem#35....

That is really cool!! it was on my TODO list, github action looks promising but I do not know yet the limitations. I have some question but I will do it directly on your repo.

**Comment by arokem** [comment]
Awesome. Thanks for doing all this! 

👍 from me for the merge. Anyone else want to take a look?

**Comment by Garyfallidis** [comment]
Let's keep some convention on the names to fbvals rather than bvals when we use get_fnames.

**Pull request merged**
