### PR TITLE
NF: Fetch and Read the MNI T1 and/or T2 template.

### PR DESCRIPTION
**Pull request by arokem**
While I was there, I did a bit of PEP8 cleaning and functionalized some repeated boiler-plate.

### CODE REVIEW

**Comment by Garyfallidis** [comment]
Nice job!

**Comment by Garyfallidis** [comment]
@villalonreina you can now update this file to also download the tissue maps from MNI. 
Also @arokem do we need to add some license info for these?

**Comment by arokem** [comment]
License info is included! But let me know if this seems insufficient, and
we'll fix:

https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L567
https://github.com/nipy/dipy/blob/master/dipy/data/fetcher.py#L586

**Comment by Garyfallidis** [comment]
We need to add a printout to say that by downloading this dataset you agree to this license found there... or something.

**Comment by arokem** [comment]
Note that I have mirrored all the files here:

https://digital.lib.washington.edu/researchworks/bitstream/handle/1773/33312/

so that we can grab individual files, rather than a big archive with all of
them.

**Comment by arokem** [comment]
Read the license - I don't think it requires that.

**Comment by Garyfallidis** [comment]
Okay. Maybe they want us to cite some of their papers?

**Comment by arokem** [comment]
Yes - we should do that. Adding.

**Pull request merged**
