### PR TITLE
Allow PRE=1 job to fail  

### PR DESCRIPTION
**Pull request by skoudoro**
To follow the suggestion on #1579,  This PR allow `PRE=1` to fail.

### CODE REVIEW

**Comment by arokem** [comment]
What do you think, @matthew-brett? Would this be too subtle?

**Comment by matthew-brett** [comment]
I think that's fine, as long as we check from time to time...  Obviously before a release.

**Comment by skoudoro** [comment]
If we all agreed, I think this PR is ready to go @arokem. We need to put a note on the documentation.

**Comment by arokem** [comment]
Would you mind adding a note in https://github.com/nipy/dipy/blob/master/doc/devel/make_release.rst ?

**Comment by arokem** [comment]
Thanks!

**Pull request merged**
