### PR TITLE
Possible fix for the inline compilation problem

### PR DESCRIPTION
**Pull request by nilgoyette**
I'm not sure this will actually fix the problem because I have several others problems on Windows here. This PR is more of a way to test on your server.

### CODE REVIEW

**Comment by skoudoro** [comment]
I try it, and it resolved the compilation error, but you have to add this change on the `pyx` file too.

**Comment by nilgoyette** [comment]
I did as you requested, but why did you tell me `to add this change on the pyx file too`? Was there a warning or an error for one of the OS?

**Comment by nilgoyette** [comment]
The red X only mean that the test coverage decreased, right?

Is there anything else I can do? If not, we (Imeka) look forward to work with PFT so it would be nice if this commit can get merged.

**Comment by skoudoro** [comment]
Hi @nilgoyette,

> Was there a warning or an error for one of the OS?

warning on my Windows machine, I would like to understand why because it is really strange. Anyway, merging.

**Pull request merged**
