### PR TITLE
Fix missing documentation content

### PR DESCRIPTION
**Pull request by skoudoro**
All dipy.*.utils (ex: dipy.tracking.utils) are missing on the documentation so this PR change the regular expression to make this files available on api reference. (see #322)

### CODE REVIEW

**Comment by skoudoro** [comment]
I should add a modification for resolving #570 at the same time

**Comment by arokem** [comment]
Does this build the docs OK? Because full documentation building takes a while (the examples take a while to run), you can relatively quickly test this by removing most of the lines in this file: https://github.com/nipy/dipy/blob/master/doc/examples/valid_examples.txt

**Comment by skoudoro** [comment]
I just tried to generate the API reference via "make api" command, and the *.rst generated was ok.

I will generate the full documentation a little bit later to be sure that everything is ok and let you know.

**Comment by arokem** [comment]
This looks ready to go. I'll merge this, and if there are any follow-ups, we can take them on a separate PR.

**Pull request merged**
