### PR TITLE
[CI] add python3.8 matrix

### PR DESCRIPTION
**Pull request by skoudoro**
- Just add python3.8 to our CI's
- keeping python 3.5 at the moment

### CODE REVIEW

**Comment by arokem** [comment]
Nice! Only one failure! Presumably because of https://github.com/python/cpython/pull/12596. See multiple references to fixes on that PR.

**Comment by skoudoro** [comment]
Thank you for the reference!

**Comment by skoudoro** [comment]
Just quick note as reference : https://github.com/scipy/scipy/issues/10927

The minimum dependency version needed for Python 3.8:

- Numpy 1.17.3
- Scipy 1.3.2

So, updating Travis and Azure

**Comment by skoudoro** [comment]
Update:  minimum version incompatible with the `Statsmodel` package, need to update the function that uses this package.

**Comment by skoudoro** [comment]
Update:  

- tensorflow does not have wheel for python 3.8
- minimum version incompatible with the Statsmodel package, need to update the function that uses this package.

**Pull request merged**
