### PR TITLE
DOC: Update Rafael's current institution.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Update Rafael's current institution in the developers list.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@RafaelNH please check. If incorrect, amend or close. Thanks.

**Comment by RafaelNH** [comment]
Hi @jhlegarreta! Thanks for this! My current affiliation is:

Champalimaud Neuroscience Programme, Champalimaud Centre for the Unknown, Lisbon, Portugal

**Comment by jhlegarreta** [comment]
@RafaelNH Updated. Thanks !

**Comment by arokem** [comment]
Thanks for the update!

**Pull request merged**
