### PR TITLE
DOC: Fix `reconst_mapmri` example markup.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix formatting issues in the `reconst_mapmri` file to get the
documentation correctly rendered in:
http://nipy.org/dipy/examples_built/reconst_mapmri.html#example-reconst-mapmri

Changes:
- Indent lists properly.
- Indent literal blocks properly.
- Remove unnecessary double quotes for indented code/literal blocks.
- Use double backquotes for inline code samples.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Any ideas as to why the following **code block** is **not correctly rendered**?

```
We can then fit the MAPMRI model to the data.

::
    mapfit_laplacian_aniso = map_model_laplacian_aniso.fit(data_small) mapfit_positivity_aniso =
 map_model_positivity_aniso.fit(data_small) mapfit_both_aniso = map_model_both_aniso.fit(data_small) 
```

And why the **RTOP figures** are **all black** (dynamic range issues?)

Thanks.

**Comment by jhlegarreta** [comment]
This branch addresses the rendering issues reported in #1291.

**Comment by skoudoro** [comment]
> Any ideas as to why the following code block is not correctly rendered?

I think this has been corrected [here](https://github.com/nipy/dipy/commit/09a805fa63b7687ae47466ff7d6ecce9ed7f67a9#diff-aa743bb3a0919f172e5dca3244da2ab3). A "space" was missing.

>And why the RTOP figures are all black (dynamic range issues?)

No idea for the moment

**Comment by skoudoro** [comment]
can you rebase this one too @jhlegarreta? thank you

**Comment by jhlegarreta** [comment]
@skoudoro Sure.  b4eb160 was rebased on master.

**Comment by jhlegarreta** [comment]
@skoudoro Codecov reports a decrease in the coverage but this is only a documentation change, so I think this is ready to be merged

**Comment by jhlegarreta** [comment]
No worries @skoudoro. 1bee094 was rebased on top of master.

**Comment by skoudoro** [comment]
Thank you @jhlegarreta, merging !

**Pull request merged**
