### PR TITLE
Line-based version of streamline_mapping

### PR DESCRIPTION
**Pull request by nilgoyette**
I refactored the already existing line-based functions (`_streamlines_in_mask()`, `_streamline_in_mask()`) to re-use Bresenham's algorithm. This made it possible to add a line-based version of `streamline_mapping()` without too much trouble.

I'm not totally satisfied with the code because
- there's a little code copy
- `_streamline_info` is used with 2 differents goals. (useless parameters and return)
- It's somewhat slow. I don't see how I could be faster than `streamline_mapping` though because I do what it's doing + more stuff + with bigger data because we found more positions and more index.

I added a toy test AND tested with our reporting program which shows intersecting fibers. We had a lot of missing streamlines using `streamline_mapping()` on compressed fibers. The libe-based version fixes our problem perfectly; I obtain the same results as when I test all streamlines.

### CODE REVIEW

**Comment by nilgoyyou** [comment]
```
/dipy/tracking/vox2track.o -msse2 -mfpmath=sse -fopenmp
    dipy/tracking/vox2track.c:240:18: fatal error: vector: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```
Is there a problem with C++ compilation on your server? I specifically asked in `setup.py` for this file to be compiled using C++. Is it simply a problem or renaming the file from `.c` to `.cpp`?

**Comment by arokem** [comment]
Just to be clear, you are referring to this error on Travis?

https://travis-ci.org/nipy/dipy/jobs/176803157

**Comment by nilgoyyou** [comment]
Yes.

**Comment by arokem** [comment]
I am mystified. Seems to only be a problem on the `sdist` machine. I kicked that one back into action, in case this is a glitch.

**Comment by arokem** [comment]
No joy. I am not sure what's going on.

**Comment by nilgoyyou** [comment]
I don't know how to fix and I can't reproduce the error, so I simply merged the fmin fix to see if it would change anything. It probably won't.

**Comment by Garyfallidis** [comment]
@nilgoyyou and @jchoude I need some feedback with this PR. Are we on it? Or all is lost?

**Comment by nilgoyyou** [comment]
Oh, sorry, I forgot about this PR. I'll pull master and test it again.
It might give the same error which I never understood though. I'm not sure what was going on.

**Comment by nilgoyyou** [comment]
Ok, no, I don't understand.
Here's the output when compiled on your server:
```
building 'dipy.tracking.vox2track' extension
gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/home/travis/build/nipy/dipy/venv/lib/python2.7/site-packages/numpy/core/include -Ibuild -I/opt/python/2.7.9/include/python2.7 -c dipy/tracking/vox2track.c -o build/temp.linux-x86_64-2.7/dipy/tracking/vox2track.o -msse2 -mfpmath=sse -fopenmp
dipy/tracking/vox2track.c:240:18: fatal error: vector: No such file or directory
```
And on my VM
```
cythoning dipy/tracking/vox2track.pyx to dipy/tracking/vox2track.cpp
building 'dipy.tracking.vox2track' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Isrc -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -Ibuild -I/usr/include/python2.7 -c dipy/tracking/vox2track.cpp -o build/temp.linux-x86_64-2.7/dipy/tracking/vox2track.o -msse2 -mfpmath=sse -fopenmp
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/dipy/tracking/vox2track.o -o build/lib.linux-x86_64-2.7/dipy/tracking/vox2track.so -fopenmp
```
Notice the first pass of `gcc`, then `c++` All the other builds look like that, except `sdist`.
I can't reproduce this error with `python setup.py sdist` or `python setup_egg.py sdist`. `install` also work. Everything I test finishes without error. I could at least try to fix it myself if I was able to reproduce it.

Someone have an idea?

**Comment by MarcCote** [comment]
I remember that I had some problem with Cython/C++ when I implemented the clustering framework :( .

**Comment by MarcCote** [comment]
What version of Cython do you have installed on your WM?

**Comment by nilgoyyou** [comment]
I tested with version 0.24 and 0.25.2; they both work well.

**Comment by nilgoyette** [comment]
Since I don't know how to fix this and nobody knows, I'll try to remove the C++ requirement and use only normal cython. I can probably replace the std::vector with a reusable ndarray. I'll try that in the next weeks.

**Comment by nilgoyette** [comment]
I'll close this PR for now because it took too long and I have no immediate plans to do it. I'll probably clean  it and re-open it someday.

**Pull request closed without merging**
