### PR TITLE
ENH: avoid log zero

### PR DESCRIPTION
**Pull request by arokem**
This continues #1086

### CODE REVIEW

**Comment by arokem** [comment]
Let's see how our minimal numpy does with this...

**Comment by arokem** [comment]
Looks like it did OK. @jchoude : what do you think about this solution?

**Comment by jchoude** [comment]
Seems all good to me! I can merge if you want. Do we mind if the coveralls check did not pass (-0.002% difference)

**Comment by arokem** [comment]
I think that coveralls is complaining because we added four lines of code, but didn't add tests. So the difference is negative, if tiny. I wouldn't worry about it. That said, I now added a test with zeros as input, to make sure that the warning is properly suppressed, and that the result is correct.

**Comment by jchoude** [comment]
Ok! I'll wait until Travis reports back, and then I'll merge this and close my original PR.

**Comment by jchoude** [comment]
Seems all good!

**Comment by jchoude** [comment]
Thanks @arokem !

**Pull request merged**
